landlab/io/netcdf/_constants.py, landlab/io/netcdf/write.py
Fixed a bug that caused errors when writing `boolean` values to netcdf4 format. This address issue #90, which deals with writing `int64` values to netcdf3. Since netcdf3 doesn't support `int64`, netcdf4 must be used but the netcdf4 writer didn't properly deal with `boolean` types. `boolean` types are now written to netcdf as one-byte integers.
In addition, if units are not given for a field, use "?".
=> Fix writing boolean fields to netcdf

landlab/components/gFlex/flexure.py, landlab/components/single_vegetation/single_vegetation_field.py, landlab/components/single_vegetation/vegetation_multi_pft.py, landlab/components/single_vegetation/vegetation_multi_pft_new.py, landlab/components/vegetation_ca/CA_Veg.py, landlab/components/vegetation_ca/CA_Veg_new.py, landlab/grid/raster.py, landlab/grid/raster_funcs.py
This pull request fixes the failing unit tests (#95).
Fixes include:
* For `gFlex` component, issue warning to stderr rather than stdout.
* For `raster.py`, import `RasterModelGrid` in doctests.
* For `vegetation_ca` and `single_vegetation` components I've completely removed some of the doctests. They appeared to be out-of-date and no longer work.
@saisiddu, please note that I've removed some doctests for `vegetation_ca` and `single_vegetation` components. Some of these components now take an extra `dict-like` argument to their `__init__` method, which was not longer provided. Another was missing a required field in its input grid. When you have a chance, these doctests should really be added back and updated for the new classes.
=> Fix issue #95 (failing units tests)

landlab/io/netcdf/__init__.py, landlab/io/netcdf/read.py, landlab/io/netcdf/tests/test_read_netcdf.py, landlab/io/netcdf/tests/test_write_netcdf.py, setup.py
The `landlab.io.netcdf.read_netcdf` function was in need of better documentation and examples. This pull request tidies-up and adds documentation to the docstring for `read_netcdf`. In addition, it adds doctest examples that create a `RasterModelGrid` from some example netcdf files.
=> Added doctests and more documentation for read_netcdf

MANIFEST.in, landlab/components/flexure/cfuncs.pyx, landlab/components/flow_routing/cfuncs.pyx, landlab/components/flow_routing/flow_direction_DN.py, landlab/components/flow_routing/weavefuncs.py, landlab/components/stream_power/cfuncs.pyx, landlab/components/stream_power/fastscape_stream_power.py, landlab/components/stream_power/stream_power.py, landlab/components/stream_power/weavefuncs.py, setup.py
Converts @SiccarPoint's weave code to cython. Using Cython will make distributing landlab binaries easier and make us compatible with Python 3 again.
I've moved the weave code into modules called `weavefuncs.py` and added the cython code in modules called `cfuncs.pyx`. You can toggle between the weave and cython methods by setting the `methods` flag above the weave/cython blocks in the code. I've verified that the cython matches the weave byte-for-byte for the provided examples and that there isn't loss of speed. I'll wait for @SiccarPoint's go-ahead before merging this pull request and, if everything checkouts out, I'll remove the weave code so that only cython is used.
Components affected are:
* flow_routing
* stream_power
* flexure
=> Convert weave to cython

setup.py
Changed `cython` to be a requirement for setup but not for installation. This fixes installation issues on certain combinations of Python distributions and operating systems.
This also fixes an installation error that appeared with a new version of `setuptools` (version 18.0 seemed to be the culprit). When installing with setuptools 18.0, the installation would result in the following error,
AttributeError: Extension instance has no attribute '_convert_pyx_sources_to_lang'
=> Change cython to a setup requirement

docs/dev_guide_install.rst, scripts/dist_to_pypi.sh
#130 and #131.
Adds documentation that describes how to:
* run the doctests and unittests
* build wheel distributions
* use Landscape
=> Better documentation for testing and building wheels

appveyor.yml, landlab/components/flow_routing/flow_direction_DN.py, landlab/core/utils.py, landlab/grid/base.py, landlab/grid/raster.py, landlab/grid/structured_quad/links.py, landlab/grid/unstructured/links.py, landlab/grid/voronoi.py, landlab/utils/count_repeats.py, landlab/utils/structured_grid.py
This pull request fixes the failing tests on Windows. All of the failures were the result of arrays of landlab element ids being different flavors of `int`. On some systems, functions like `numpy.bincount` return arrays with `dtype=intp`, which may or may not be the same as a regular `int`. The new function `landlab.core.utils.as_id_array` converts an array to a standardized array of ids. For landlab, this is an array with `dtype=int`. Where possible, the new array is just a view of the original but, sometimes, it's necessary to create a new array.
=> Fix failing unit tests on Windows

requirements-docs.txt
The docs are not building on readthedocs. It seems readthedocs is having trouble installing the netCDF package.
=> Fix failing docs build

.ci/appveyor/deploy_to_pypi.ps1, .travis.yml, appveyor.yml
This pull request adds OSX builds to Travis (#75). Our tests are now run on: linux, Mac, and a range of numpy versions for each of these operating systems. If the tests run on a tagged release, and all the tests pass, a source and binary distribution is automatically deployed to the Python Package Index.
There seems to be a problem with Python 2.6 and numpy version 1.9 on Mac (at least as provided by Anaconda). I'm just allowing this single test to fail. If it becomes a problem later, we can look into what's causing it to fail.
=> Add OSX builds to Travis

landlab/grid/base.py
This pull request make the array returned by `status_at_link` read-only. The status of links should be the result of the status of their head and tail nodes.
=> Make status_at_link array read-only.

landlab/grid/base.py, landlab/grid/tests/test_raster_grid/test_fixed_link_boundary.py
This pull resolves an issue where it was not possible to change a node
at the end of a fixed link to a fixed value node. It is now possible.
Note it is *still* impossible, by necessity and by design, to set a
node at the end of a fixed link to closed. You need to convert the
fixed link to a regular open (or closed) link first.
=> Fixed link-fixed value node conflict

landlab/components/detachment_ltd_sed_trp/generate_detachment_ltd_transport.py, landlab/components/flexure/examples/example_two_point_load.py, landlab/components/flow_accum/flow_accumulation.py, landlab/components/flow_accum/flow_accumulation2.py, landlab/components/pet/examples/potential_evapotranspiration_field_example.py, landlab/components/radiation/examples/radiation_field_example.py, landlab/components/sed_trp_shallow_flow/transport_sed_in_shallow_flow.py, landlab/components/simple_power_law_incision/power_law_fluvial_eroder.py, landlab/components/simple_power_law_incision/power_law_incision_driver.py, landlab/components/simple_power_law_incision/power_law_incision_driver_side_outlet.py, landlab/components/stream_power/examples/test_script_for_fastscape_stream_power.py, landlab/components/stream_power/sed_flux_dep_incision.py, landlab/components/stream_power/stream_power.py, landlab/components/transport_limited_fluvial/tl_fluvial_monodirectional.py, landlab/components/transport_limited_fluvial/tl_fluvial_monodirectional_alt.py, landlab/components/transport_limited_fluvial/tl_fluvial_monodirectional_v3.py, landlab/components/transport_limited_fluvial/tl_fluvial_polydirectional.py, landlab/examples/slope_aspect_routines_comparison.py, landlab/grid/base.py, landlab/grid/grid_funcs.py, landlab/grid/raster.py, landlab/grid/structured_quad/cells.py, landlab/grid/structured_quad/faces.py, landlab/grid/voronoi.py, landlab/plot/__init__.py, landlab/plot/imshow.py, landlab/plot/tests/test_imshow_grid.py
This pull request fixes #171. The main change is to the `_reset_lists_of_nodes_cells` method of `ModelGrid`. However, in fixing this I also removed arrays that used old terminology. These include:
- `activecell_node`
- `node_corecell`
- `corecell_node`
- `node_activecell`
- `active_cell_areas`
Many of these arrays were still being used in `VoronoiDelaunayGrid` so maybe @gregtucker you could have a look?
One bit of confusion is that I'm not sure if we have a name for a node that is either *core* or *open boundary*? It seems these used to be *active*.
=> Fix _reset_lists_of_nodes_cells

landlab/components/craters/craters.py, landlab/components/delta_front/delta_front.py, landlab/components/flow_routing/flow_direction_DN.py, landlab/components/flow_routing/lake_mapper.py, landlab/components/nonlinear_diffusion/Perron_nl_diffuse.py, landlab/components/sink_fill/fill_sinks.py, landlab/components/transport_limited_fluvial/tl_fluvial_monodirectional_alt.py, landlab/components/transport_limited_fluvial/tl_fluvial_monodirectional_v3.py, landlab/components/transport_limited_fluvial/tl_fluvial_polydirectional.py, landlab/grid/base.py, landlab/grid/raster.py, landlab/grid/raster_aspect.py, landlab/grid/raster_funcs.py, landlab/grid/raster_gradients.py, landlab/grid/raster_steepest_descent.py, landlab/grid/tests/test_raster_grid/test_init.py, landlab/grid/tests/test_raster_grid/test_neighbor_nodes.py, landlab/utils/fault_facet_finder.py
The pull request adds a new property for getting node neighbors and renames an existing method that gets *active* neighbors.
A *neighbor* is the node on the other end of a link. An *active neighbor* is the node on the other end of an *active* link.
Added `ModelGrid.neighbors_at_node` attribute. Note that, thus far, this is only implemented for a `RasterModelGrid`. Other grids need to define their own `_neighbors_at_node` array. Until that's done, for those grids, using `neighbors_at_node` will raise an `AttributeError`.
Renamed `get_neighbor_list` method to `get_active_neighbor_at_node`.
=> Add neighbors_at_node property

landlab/testing/nosetester.py, landlab/utils/decorators.py, scripts/test-installed-landlab.py
This pull request fixes the `test-installed-landlab.py` script. Doctests for functions that were decorated with a decorator defined in another module were not being run. This is fixed by creating a custom `LandlabDoctest` plugin for finding and running doctests.
Other changes:
* `+NORMALIZE_WHITESPACE` is now the default
* Warnings (including `DeprecationWarning`) are not turned into errors
=> Fix the landlab testing script

landlab/components/flow_accum/flow_accumulation.py, landlab/components/flow_accum/flow_accumulation2.py, landlab/components/stream_power/sed_flux_dep_incision.py, landlab/components/transport_limited_fluvial/tl_fluvial_monodirectional.py, landlab/components/transport_limited_fluvial/tl_fluvial_monodirectional_alt.py, landlab/components/transport_limited_fluvial/tl_fluvial_monodirectional_v3.py, landlab/components/transport_limited_fluvial/tl_fluvial_polydirectional.py, landlab/grid/base.py, landlab/grid/grid_funcs.py, landlab/grid/hex.py, landlab/grid/tests/test_raster_grid/test_cell_areas.py, landlab/grid/tests/test_raster_grid/test_link_length.py, landlab/grid/voronoi.py, landlab/plot/channel_profile.py
This pull request fixes #201.
Both the `cell_areas` and `area_of_cell` attribute was being used. This removes `cell_areas` in favor of `area_of_cell`. We should decide on what we want to call these sorts of arrays (another example is `link_length` vs. `length_of_link` or similar). It's easy enough to change.
I chose `area_of_cell` because it more closely follows our element id naming convention (`node_at_cell`, `links_at_node`, etc.). The name is divided by `_at_`, the first part is the quantity and the second part the name of the element (which also indicates how long the returned array is).
=> Fix Voronoi cell areas

landlab/grid/raster.py, landlab/io/netcdf/tests/test_write_netcdf.py, landlab/io/netcdf/write.py
This pull request adds the capability to print cell grids to NetCDF files. A deficiency that was reported by @lgelb in #221. The format follows the [cfconventions for cell data] (http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#idp5784080).
The `write_netcdf` function and the `save` method of `RasterModelGrid` now accept a keyword, `at`, to specify which values should be written. `at` can be either `None`, `'cell'`, or `'node'` (`None` means to guess the location based on the requested field names). Note that values at either cells or nodes can be written to a single file. If you want to write values at nodes and cells, you'll have to do it in two separate files.
If there's no ambiguity of what values to print, the `at` keyword is not needed. …
=> Add support for writing cell grids to NetCDF

landlab/components/flow_routing/lake_mapper.py, landlab/components/stream_power/fastscape_stream_power.py, landlab/components/stream_power/stream_power.py
Modified FastscapeStreamPower's erode method to optionally take a list of flooded nodes, and set their alpha values to zero, which forces them to have no erosion (which would actually be reverse erosion where the receiver node is higher than the donor)
=> Gt handle flooded nodes in stream power

landlab/core/utils.py, landlab/grid/gradients.py, landlab/grid/mappers.py, landlab/grid/raster_gradients.py, landlab/grid/raster_mappers.py
Resolve documentation booboo where funcs that get automatically imported from mappers.py and gradients.py into the grid retain “grid” as the first entry in their Parameters in the docstrings.
=> Add func to strip grid from docstring if func is imported to grid

landlab/core/model_parameter_loader.py, landlab/core/tests/test_load_params.py
Fixes #268.
Fixes the `load_params` function so that it can now read YAML or MPD-formatted files as:
* file-like objects
* path to an existing parameter file
* contents of a parameter file
Added unit tests for the above cases.
=> Fixed load_params

landlab/components/chi_index/channel_chi.py, landlab/components/diffusion/diffusion.py, landlab/components/overland_flow/generate_overland_flow_Bates.py, landlab/components/overland_flow/generate_overland_flow_deAlmeida.py, landlab/components/steepness_index/channel_steepness.py, landlab/components/stream_power/tests/test_voronoi_sp.py, landlab/grid/base.py, landlab/grid/divergence.py, landlab/grid/gradients.py, landlab/grid/grid_funcs.py, landlab/grid/mappers.py, landlab/grid/raster.py, landlab/grid/raster_funcs.py, landlab/grid/raster_gradients.py, landlab/grid/tests/test_raster_funcs/test_gradients_at_active_links.py, landlab/grid/tests/test_raster_grid/test_init.py, landlab/plot/imshow.py, landlab/plot/video_out.py, landlab/tests/speed_test_model_grid.py, landlab/utils/decorators.py, landlab/utils/fault_facet_finder.py
This pull request removes usages of many (but not all) deprecated functions/methods. Most of the remaining usages are either private methods, in doctests for the deprecated functions themselves, or not straightforward to convert to an alternative.
Note that in this pull request I have disabled warnings for methods that start with an underscore. This can easily be turned back on.
@SiccarPoint: One problem I had was with active links. The `active_links` attribute doesn't seem to ever include active *diagonal* links. This is a problem when replacing `grid.calc_grad_at_active_link()` with `calc_grad_at_link()[grid.active_links]`.
@saisiddu: In the radiation component when I switched from,
```python
self._slope, self._aspect = grid.calculate_slope_aspect_at_nodes_burrough(vals='topographic__ele …
```
=> Remove usages of deprecated functions

landlab/components/chi_index/channel_chi.py, landlab/components/flow_routing/flow_direction_DN.py, landlab/components/flow_routing/lake_mapper.py, landlab/components/steepness_index/channel_steepness.py, landlab/components/stream_power/examples/test_script_for_fastscape_stream_power.py, landlab/components/stream_power/fastscape_stream_power.py, landlab/components/stream_power/sed_flux_dep_incision.py, landlab/components/stream_power/stream_power.py, landlab/grid/base.py, landlab/grid/raster.py, landlab/grid/raster_gradients.py, landlab/plot/channel_profile.py
As noted by user Laijingtao, there are potential issues around our
handling of `length_of_link` on rasters once diagonal links are created.
Formerly, `length_of_link` would be extended with diagonal links if
they had been created. This was documented, but was not obvious
behaviour. Now, this behaviour is only performed by the new internal
property, `_length_of_link_with_diagonals`. `length_of_link` itself
always now only returns the lengths of “true” Landlab links.
Code base updated so that the existing methods using `length_of_link`
now point to the right variant.
Note that the internal property will be removed along with all
RasterModelGrid class diagonal properties once a child class handling
diagonals explicitly exists.
=> Resolve issues around `length_of_link`

landlab/components/diffusion/diffusion.py, landlab/grid/raster.py, landlab/grid/tests/test_raster_grid/test_link_length.py
length_of_link now behaves internally consistently. It always returns
the number of true links, including on first call.
Also resolve associated issue where it was possible to begin using some
diagonal methods on the raster without having created all of the
diagonal link structures.
=> Resolve bug

landlab/ca/celllab_cts.py, landlab/ca/cfuncs.pyx, landlab/ca/tests/test_celllab_cts.py
This PR fixes a bug in which the "run" method in CellLab CTS could run further than its "run_to" parameter, if an event occurred later. Also cythonizes another function. test-installed-landlab passes.
=> Gt debug cts

landlab/components/gflex/flexure.py
This pull removes the annoying warning for users who haven’t installed gFlex. (I think)
=> Strip gFlex warning from launch if no gFlex present

landlab/components/flow_accum/cfuncs.pyx, landlab/components/flow_accum/flow_accum_bw.py, setup.py
Implements cython for the recursive flow accumulation method
`add_to_stack`, aiming to fix Kelly’s issues with hitting Python’s
inbuilt recursion limit. Also seems to accelerate the component
significantly.
This changes duplicated in a pull about to go in to the master branch.
=> Implement cython for flow_accum_bw

landlab/components/flow_routing/lake_mapper.py
This PR just adds some diagnostic output for the case when the lake-fill algorithm can't find an outlet. This can happen if, for example, the user accidentally passes it a watershed DEM with no outlet node(s) specified (i.e., surrounded by closed nodes), or if there is an isolated pocket of core node(s) surrounded by closed boundary nodes.
=> Gt fix lake bug

landlab/field/field_mixin.py, landlab/grid/base.py, landlab/grid/hex.py, landlab/grid/radial.py, landlab/grid/raster.py, landlab/grid/tests/test_raster_grid/test_corners.py, landlab/grid/voronoi.py
This pull request add fields for both *patches* and *corners*. The following should now work,
```python
>>> from landlab import RasterModelGrid
>>> grid = RasterModelGrid((4, 5))
>>> grid.add_ones('z', at='corner')
>>> grid.at_corner['z']
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
```
and likewise for *patches*. We can now create fields for:
* *nodes*, *links*, *patches*, and
* *corners*, *faces*, *cells*
=> Add fields for patches and corners

landlab/components/__init__.py, landlab/components/fire_generator/generate_fire.py, landlab/components/uniform_precip/generate_uniform_precip.py
A quick addition of a standard interface on PrecipitationDistribution.
Just because it’s not spatially resolved and doesn’t use fields,
doesn’t mean it shouldn’t have a LL interface indicating as much…
=> Make PrecipitationDistribution a component

landlab/field/field_mixin.py, landlab/field/grouped.py, landlab/grid/base.py, landlab/grid/tests/test_raster_grid/test_fields.py, landlab/grid/voronoi.py
This pull request removed unsized fields for the core `ModelGrid` elements. That is, `node`, `link`, `patch`, `corner`, `face`, and `cell`. There are still fields for elements like `active_link`, `core_node`, etc. Since the size of these fields can change after the grid has been created, they need to be flexible in their size.
=> Remove unsized fields

landlab/components/flow_routing/route_flow_dn.py
This ends up only changing one field, in flow routing: flow__sink_flag is now int8 rather than int. Changing element index fields from int (64) to numpy.int32 turns out to be problematic because it's wired into a lot of cython stuff, such as Fastscape, flow routing .pyx files, etc. Bigger job than I have time for now.
=> Gt change flow routing fields to int32

landlab/components/overland_flow/tests/test_dealmeida_overland_flow.py, landlab/field/field_mixin.py, landlab/grid/base.py, landlab/grid/gradients.py, landlab/grid/raster.py, landlab/grid/raster_gradients.py, landlab/grid/tests/test_raster_grid/test_allocators.py
This pull request completely removes field locations for `active_links`, `active_faces`, `core_nodes`, and `core_cells`.
@jadams15: The biggest change, which actually isn't all the big, is in the unit tests for your overland flow component. Maybe you could have a look at see if it's fine?
=> Remove active link fields

landlab/components/flow_routing/lake_mapper.py, landlab/components/flow_routing/tests/test_lake_mapper.py
This PR fixes a bug in the lake mapper. Basically, the issue was as follows: sometimes the potential outlet node of a lake lies above a neighboring node that itself is flooded in a different lake. Until now, this was handled by saying "if the neighbor node is flooded, you (the potential outlet) can't drain to it" -- even if the water level lies below the potential outlet. This had the odd side effect of producing (in certain cases) negative depression depths. A solution is to consider a flooded neighbor to be a valid potential outlet IF its own outlet lies below the new outlet being considered. The logic adds a potentially expensive loop, but it is only invoked if there is at least one flooded node neighboring the potential outlet.
=> modify node_can_drain method

landlab/components/uniform_precip/generate_uniform_precip.py
Two minor changes to the PrecipitationDistribution component:
1) storm and interstorm duration are no longer rounded to 2 decimals (which I think removes the need to test for zero durations)
2) the generator function now allows the possibility for the sequence to end in the middle of a storm (previously, if time ran out during a storm, it would still return a zero-duration interstorm period, which had the odd side effect of forcing a model to always have zero precipitation just before an output to file)
=> precip gen: don't round; allow generated to sequence to end in a storm

landlab/field/field_mixin.py, landlab/field/grouped.py, landlab/field/scalar_data_fields.py, landlab/field/tests/test_grouped_fields.py, landlab/grid/base.py, landlab/grid/tests/test_raster_grid/test_fields.py
To discuss and potentially change from this pull request:
1) Name. I’ve used “at_everywhere” because to keep in line with the current code used to set/test the size of controlled field groups I needed to create a property that mirrored the existing properties grid.number_of …  grid.number_of_value_at_everywhere is imperfect, but it is the best thing that I could come up with. If anyone has a better idea for how to name this, please let me know. 
2) Value or array. At the moment,  I’ve mirrored the other controlled field groups (at_node, at_cell, etc) in that this field group must be made of arrays of length 1. One could argue that this field group should be required to be str, int, float, or bool, rather than an array of length one. I wasn’t sure which was best, so I’ve implemented the …
=> Adding a field group "at_everywhere" to store single element arrays meant to represent values global to the grid. 

landlab/components/__init__.py, landlab/components/depth_dependent_diffusion/hillslope_depth_dependent_linear_flux.py, landlab/components/weathering/__init__.py, landlab/components/weathering/exponential_weathering.py
Some syntactical and PEP8 edits to RCG's Depth-Dependent Diffusion and Expo Weathering components.
@kbarnhart when you review this could you get Rachel to look over your shoulder? Want to make sure she's on board. Edits are mostly to do with var naming. Parameter names should mirror those used in input files, and longer descriptive names are generally better than names like "k". I changed "weathering" to "soil production" because geochem folks have other meanings for "weathering" (of course soil scientists might not like "soil production" either, but "mobile regolith production" seems too long)
=> edit depth-dep prod and wxing

landlab/components/drainage_density/drainage_density.py
I made the requested change that allows users to specify a channelization threshold rule of the form aA^(b)*cS^(d)>thresh, if they don't want to supply a channel mask. The component throws an error if neither approach is taken. It'd be great if @mcflugen and @gregtucker would take a look at this and then merge if all looks OK.
=> Updates to drainage density component

docs/landlab.components.stream_power.rst, landlab/components/stream_power/fastscape_stream_power.py
FastscapeEroder has an assert to test assumption that if rainfall_intensity is not a field (name, array, etc.), then it is either float or int. But it's possible for a driver to have it be a numpy.float64. That's now added.
Also changed an outdated doc comment saying (incorrectly) that StreamPowerEroder doesn't use fastscape algo.
By the way, why do we have 2 stream power components that use the same algo?
=> fastscape assert now passes float64; also tiny doc tweak

landlab/grid/raster.py
Minor changes to fix `set_watershed_boundary()` (see issue #425).
An outstanding question:
I have not grappled with _which_ of multiple minimums may be selected.
If a grid has two minimums, and only one is adjacent to a boundary, this one will be chosen.
However, if both minimums are on a boundary, then the FIRST one returned by np.where() is the one that `set_watershed_boundary()` will set as the outlet_node and with status `FIXED_VALUE_BOUNDARY`
I suggest we discuss if this should be tested for and how it should be handled.
=> Fixing the set_watershed_boundary() issue identified in #425 

.conda-recipe/meta.yaml
This PR kind of fixes issue #432. The problem is that installing from the default Anaconda channel (installing from the conda-forge channel works) creates a version conflict (between numpy-1.11, jpeg-9b, and hdf4-4.2.12) when using netcdf4-1.2.4. This seems to only be a problem on Mac and Linux and numpy-1.11.
I've added a requirement in `meta.yaml` for `hdf4 >= 4.2.12` for the problem build cases. I hope this will resolve itself and, in the future, we can remove this requirement. Anyway, this should get our builds on `master` passing again.
=> Fix issue 432

landlab/components/stream_power/stream_power_smooth_threshold.py
o Fixes a mistake in smooth-threshold stream power solver ("epsilon" includes elevation of downstream receiver node, and so needs to be calculated within the node loop rather than ahead of time)
o Enables possibility of passing an array or field name to use in place of drainage area (i.e., a field to use as discharge)
=> Gt add q stream power smooth thresh

landlab/components/stream_power/cfuncs.pyx
The problem: when n is not an integer and flat or negative slopes are present (e.g., there are pits/lakes), the solver was choking and generating nans. Now screened to invoke the solver at a node pair only when the source node is higher than its receiver node.
Note: when I ran tests I got a batch of netCDF4-related errors, which do not seem to be related to this fix.
=> add check on flat/negative slope in stream power solver

landlab/grid/base.py, landlab/grid/tests/test_raster_grid/test_BC_updates.py
This pull request is intended to fix issue #428.
I've made only a small change in `_update_links_nodes_cells_to_new_BCs`. Now the active link directions are rest to the link directions and then the active link directions are reset based on the current boundary conditions.
I also added a couple tests that reproduce the two issues described in #428.
=> Fix issue #428

.gitignore, landlab/components/stream_power/fastscape_stream_power.py, landlab/components/stream_power/stream_power_smooth_threshold.py
Minor change to FastscapeEroder: previously, when user passes an array as K_sp, the component makes a copy. Better if the user can change the K_sp field dynamically, however. Now changed to use a reference to the passed K_sp array, so if user changes the array, FastscapeEroder will "see" the changes.
@kbarnhart or @SiccarPoint could you take a quick look and merge please?
=> Gt fix fastscape variable k

landlab/components/diffusion/diffusion.py, landlab/components/diffusion/tests/test_sniff_diffusion.py
deposit flag added to linear diffusion for new option to make diffusion only erode. Material that would be deposited 'disappears' - presumably because it is taken up by fluvial channels.
=> no deposit option for linear diffusion

landlab/components/__init__.py, landlab/components/overland_flow/__init__.py, landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py, landlab/components/overland_flow/tests/test_kinwave_implicit.py
This is a new component that implements an order-N "node by node" implicit solution to the kinematic wave approximation of the shallow-water equations. The basic idea is that if you can process the nodes in upstream-to-downstream order, you can always know the inflow discharge at a particular node. With that, and assuming that the depth of water at the node sets the outflow to the adjacent downhill nodes, it's possible to do an implicit solution for water depth at the new time step. Here, more generally, it's weighted between H at the new and old time steps, with a user-specified weight factor. The algorithm uses the MFD FlowAccumulator, which is order-N. Moreover, the algorithm itself should be order-N, since it sweeps through nodes once.
=> add basic version of implicit kinwave model

landlab/components/flow_accum/flow_accum_to_n.py
An stack issue was found while working on a side project. When using
route-to-multiple, sometimes node ids can be added twice. Pre-existing
code to fix this was not working in an application. This code fixes the
issue in the application.
=> Changes to flow_accumulation stack construction

landlab/components/hybrid_alluvium/hybrid_alluvium.py
This subset of float conversions are superseded by code just below this block that tests for different possible input types (e.g. field name as a string).
@cmshobe could you add some tests that include providing K_sed, K_br, sp_crit_sed, sp_crit_br as float, field name, or array so that tests test this functionality. Also a test that provides something you expect to break this functionality.
=> Removing unnecessary lines in HybridAlluvium component

.conda-recipe/meta.yaml, requirements.txt
This pull request fixes an issue on OSX where `netCDF4` (from the default conda channel - netcdf4 from PyPI and conda-forge are fine) fails to import with `numpy==1.11` installed. The reported error is:
```
Library not loaded: @rpath/libjpeg.8.dylib
```
It seems that the netcdf4 package on Anaconda was build with `jpeg==8` but the default version is now 9. This pull request simply specifies jpeg version 8 as a requirement in the conda build recipe for OSX with numpy 1.11.
=> Fix netcdf4 import error

landlab/plot/event_handler.py, landlab/plot/imshow.py, landlab/plot/tests/test_event_handler.py
This pull request includes a new file, `landlab.plot.event_handler` for matplotlib events. The sole function (so far) prints node coordinates when users mouse press imshow figures. This function is attached to a figure in `landlab.plot.imshow.imshow_grid_at_node`.
=> imshow grid query on mouse button press

landlab/components/flow_director/flow_direction_dinf.py, landlab/components/flow_director/flow_direction_mfd.py, landlab/components/flow_director/flow_director_dinf.py, landlab/components/flow_director/flow_director_mfd.py
Previously FlowDirectorDINF and FlowDirectorMFD created
“flow__link_to_receiver_node” and if the node flowed to itself, set the
value to -1. This is different than how the flow-director to one
methods work (value was set to node-id value).
This discrepancy was discovered by @amanaster2 while trying to use the
implicit kinematic wave component (which relies on flow director MFD)
along with the fastscape stream power component (which expects
flow-to-self nodes to have node id as the receiver not -1) (PR #507)
This commit should fix this issue. @amanaster2 - want to check out this branch and test that it addresses your problem.
=> Changing the default behavior of FlowDirectors to many (DINF and MFD)

landlab/components/soil_moisture/infiltrate_soil_green_ampt.py
This pull request fixes the error reported by #530. That is, a shape mismatch between arrays when running the `run_one_step` method in `SoilInfiltrationGreenAmpt`.
The actual infiltration rate is now calculated using water depths only at nodes given by `full_infil_indx`.
=> Fix SoilInfiltrationGreenAmpt issue #530

landlab/grid/hex.py
Allows specifying different colormap in hexplot. This fix should make PR #503 obsolete.
=> enable dift colormap in hexplot

landlab/components/depth_dependent_cubic_soil_creep/hillslope_depth_dependent_cubic_flux.py, landlab/components/depth_dependent_cubic_soil_creep/tests/test_depth_dependent_cubic_diffuser.py
This PR addresses Issue #547 . It removes the option to pass `**kwargs` to the Depth Dependent Cubic Diffuser and adds a test that demonstrates that passing an unnecessary keyword argument will now raise a `TypeError`
=> Addressing Issue #547 **kwargs in Depth Dependent Cubic Diffuser

landlab/components/space/space.py
Porosity factor 1 / (1-phi) had been included in SPACE's default solver, but not in the adaptive solver. Now corrected.
=> incorporate porosity (phi) in SPACE's adaptive solver option

requirements-docs.txt
This pull requests addresses #575. It appears that somewhere along the way we added the `statsmodels` package as a requirement (used by `landslide_probability.py`). `statsmodels` was correctly added to `requirements.txt` but not to `requirements-docs.txt`, which are the requirements for building the documentation.
=> Add statsmodels as requirement for docs build.

landlab/components/stream_power/__init__.py, landlab/components/stream_power/fastscape_stream_power.py
This is a simple update to FastscapeEroder that allows it to take a discharge field instead of using drainage area. The implementation is simple: the component stores a string discharge_name, which defaults to 'drainage_area'. In the erode() method, the hard-coded name 'drainage_area' is now replaced by variable discharge_name. If the user passes something else for discharge_name, such as 'surface_water__discharge', this is used instead of the default 'drainage_area' field. If it doesn't exist, the user gets a key error.
Note that testing for existence of the passed field in __init__ would make some of our tests fail, because sometimes this component is instantiated before the requested field (such as 'drainage_area') is created. This is the reason for storing the name rather than the …
=> new kw arg FastscapeEroder: discharge_name

landlab/grid/base.py, landlab/grid/raster.py, landlab/grid/tests/test_raster_grid/test_init.py, landlab/grid/tests/testing_hex_grid/test_link_order.py, landlab/grid/voronoi.py
This pull request adds a `nodes_at_link` property to `ModelGrid` (issued #363). `nodes_at_link` is a index array of shape `(n_links, 2)` where the first column is the node at each link tail and the second column the node at the link head. `node_at_link_tail` and `node_at_link_head` now return views of the `nodes_at_link` matrix.
=> Add nodes_at_link

landlab/grid/raster_funcs.py, landlab/grid/tests/test_raster_funcs/test_node_id_of_adjacent.py
The pull request removes the `corner_node_at_cell` function and related tests.
This function:
* is not used within the landlab package.
* is poorly-named. "corner" here does not refer to the grid element but rather to a diagonally adjacent node.
* is redundant as it can be reproduced using existing grid data structures.
* uses a non-standard element ordering (clockwise from lower right rather than the standard counterclockwise from upper right).
=> Remove corner_node_at_cell

.travis.yml
This pull request fixes the mysterious failing Travis CI tests. Ever since Travis updated their linux images to Trusty, our linux builds have been failing with the following error,
```
error: [Errno 11] Resource temporarily unavailable
```
We're not the only ones (travis-ci/travis-ci#8934). This is fixed by adding `filter_secrets: false` to `.travis.yml` (I have no idea what this does but it does fix the problem - see this [comment](https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-321777557) in travis-ci/travis-ci#4704).
@nathanlyons this should fix the issue you describe in #603.
=> Fix "Resource temporarily unavailable" error on Travis CI

landlab/components/taylor_nonlinear_hillslope_flux/taylor_nonlinear_hillslope_flux.py
This PR fixes an issue with Taylor Nonlinear Diffuser, in which erosion/deposition was being applied to open boundary nodes. Now only applied to core nodes.
=> only apply ero/dep to core nodes

landlab/components/flow_accum/flow_accumulator.py, landlab/components/flow_accum/tests/test_flow_accumulator.py, landlab/components/flow_routing/lake_mapper.py
Addresses #611 
Now, FlowAccumulator can pass the routing keyword to DepressionFinderAndRouter.
FlowAccumulator tests that D8 DepressionFinding is not used with SteepestDescent Directions on Raster Grids.
Tests added
Few other code improvements also made (e.g. replacing type with isinstance)
=> Improvements to FlowAccumulator and DepressionFinderAndRouter

landlab/components/stream_power/fastscape_stream_power.py, landlab/plot/channel_profile.py, landlab/plot/tests/test_channel_profile.py
I started to get testing errors related to the channel profiler and `FastscapeEroder`. 
these mostly had to do with running either on a HexGrid which doesn't have the attribute `grid.length_of_d8`. I added a type check to fix this. 
a similar issue came up with the stream profiler which was using `_length_of_link_with_diagonals`, the precursor to` length_of_d8`. I also added a type check here. 
While doing this I cleaned up the lems used in the tests to make them simpler
=> Updates to channel profile and fastscape

landlab/_version.py, setup.cfg
This pull request fixes a problem where versioneer kept the "v" in our tags as part of the version number. Now versioneer ignores the "v" in our tags. So, `v1.3.0` is actually version `1.3.0`.
=> Set versioneer to ignore `v` prefix in tags

landlab/components/erosion_deposition/cfuncs.pyx, landlab/components/erosion_deposition/erosion_deposition.py, landlab/components/erosion_deposition/tests/test_erodep.py, landlab/components/erosion_deposition/tests/test_erodep_steady_state.py, landlab/components/space/cfuncs.pyx, landlab/components/space/space.py, landlab/components/space/tests/test_space.py
Addresses Issue #654
@cmshobe I'd also like your review. 
I also think that this indicates that SPACE was not using diagonal link lengths even if sediment and water were routed on diagonals. 
The tests do not pass. On my computer I get two errors that indicate VERY small differences between expected and provided. I've pasted these errors below. 
They appear to be mostly in the last few decimal places. 
We can discuss if its OK to change the expected values.
```
======================================================================
FAIL: Doctest: landlab.components.space.space.Space
----------------------------------------------------------------------
Traceback (most recent call last):
File "/anaconda3/lib/python3.6/doctest.py", line 2199, in runTest
raise …
```
=> Making space work with hexmodelgrid

landlab/components/erosion_deposition/erosion_deposition.py, landlab/components/space/space.py, landlab/components/space/tests/test_space.py
1) detachment-limited solution (slope-area model vs analytical)
2) transport-limited solution (slope-area model vs analytical)
3) mixed bedrock-alluvial solution (slope-area and sediment depth model vs analytical)
ALSO enhanced documentation for 'dicharge_field' param
ALSO removed qs_in_ext capability because @kbarnhart and I agreed to deal with that in a separate PR.
@gregtucker and @kbarnhart please review!
=> Adding 3 steady-state tests for SPACE (from the GMD paper examples)

landlab/__init__.py
This tiny pull request adds the convenience function `cite_as` to return the citations a user should use based on the components they are using.
```python
>>> import landlab
>>> print(landlab.cite_as())
```
prints
```
@article{hobley2017creative,
title={Creative computing with Landlab: an open-source toolkit
...
```
If you then instantiate a component,
```python
>>> from landlab.components import Flexure
>>> Flexure(landlab.RasterModelGrid((3, 4)))
>>> print(landlab.cite_as())
```
`cite_as` would return
```
@article{hobley2017creative,
title={Creative computing with Landlab: an open-source toolkit
...
@article{hutton2008sedflux,
title={Sedflux 2.0: An advanced process-response model that
...
```
=> Add cite_as function to landlab

landlab/io/netcdf/tests/test_write_netcdf.py
This pull request fixes several errors we have been seeing on Travis. The errors are described in #710. The fix was simply to use `flatten()` to flatten the masked arrays for comparison within the tests. The `flat` attribute was returning an iterator rather than a new array, which caused several assertions to fail.
=> Flatten masked arrays for comparison.

landlab/components/flexure/__init__.py, landlab/components/flexure/examples/example_loading_everywhere.py, landlab/components/flexure/examples/example_point_load.py, landlab/components/flexure/examples/example_random_point_loads.py, landlab/components/flexure/examples/example_two_point_load.py, landlab/components/flexure/flexure.py, landlab/components/flexure/flexure_1d.py, landlab/components/flexure/funcs.py, landlab/components/flexure/tests/test_flexure.py, landlab/components/flexure/tests/test_flexure_1d.py
This pull request fixes a small bug in the `Flexure1D` component when using the *flexure* method. The problem was that the component assumed that `x_at_node` was C-contiguous, but it wasn't. Both `x_at_node` and `y_at_node` of `RasterModelGrid` are *not* contiguous because they are views of `xy_at_node`, which is of shape *(n_nodes, 2)*.
=> Fix Flexure1D bug

landlab/ca/tests/grain_hill.py
Dis-allow plotting in two doctests that check the CA model
=> don't plot grain hill test of CA

.conda-recipe/meta.yaml, .travis.yml
pytest v3.7.3 was broken on Mac (as described in #779) so, to get our tests working, we had to specify a working version of pytest (v3.7.1) in the `.travis.yml` and the conda `meta.yaml` files. Since pytest v3.7.4 is now available on the default channel, we no longer need to specify an older version.
=> Remove version requirement for pytest

docs/index.rst, landlab/components/drainage_density/drainage_density.py
Addresses #771. There was already a drainage density .rst file, but there was no line for drainage density in the index.rst file. @jdgemperline this should make the Dd docs work (assuming the docs are working generally).
@kbarnhart check and merge as the spirit moves you
=> adding drainage density component to index.rst

landlab/data_record/data_record.py
The change I made to init options described  [in this comment](https://github.com/landlab/landlab/issues/769#issuecomment-421528527) seem to be covered by the tests you have already created, so I did not make additional tests. 
The run time improvement described in the linked comment is due to this line change in the `set data` method:
```python
time_index = int(self.time_coordinates.index(time[0]))
time_index = np.where(self.time.values == time)[0][0]
```
Questions and other minor things I hoped to save you from having to doing:
- Editted first bit of method docstrings to be limited to one line of text.
- Are the adjacent double parenthesis needed? For example:
```python
raise TypeError(('time must be a list or a 1-d array'))
```
- Are `_input_var_names`, etc necessary given that this is …
=> DataRecord init options

landlab/core/utils.py
This pull request removes `as_id_array` cruft from `landlab/utils.py` as described in #843. I've also changed `as_id_array` to return the input array when possible instead of a view. I think that should be ok. There's another doctest, which uses `np.where`, too.
=> Fix #843; remove as_id_array cruft

landlab/components/lithology/lithology.py, landlab/components/lithology/tests/test_litholayers.py, landlab/components/lithology/tests/test_lithology.py
This pull request fixes issue #861. The `Lithology` (and so `Litholayers`) component could not be wrapped with a BMI because it did not inherit from `landlab.Component`. This pull request adds:
1. `Component` as a parent to `Lithology`, and
1.  a couple tests to ensure that both `Lithology` and `Litholayers` can be wrapped with a BMI using `wrap_as_bmi`.
=> Fix issue 861

landlab/field/grouped.py, landlab/grid/hex.py, landlab/grid/raster.py
Addresses #867 
@mcflugen I did this by adding a new method to `ModelDataFieldsMixIn`.
My thinking was that I want something like the `use_field_name_or_array` decorator that can work for model grids. 
I didn't want to make an `if isinstance(field, stringtypes` block in all six watershed methods (and then to test them all). 
Note, I did not use `np.array(field).flatten()` because that returns a copy of the array.
=> Allow watershed methods to take a field name

landlab/grid/create.py, landlab/grid/raster.py, landlab/grid/tests/test_grid_reference.py, landlab/grid/tests/test_raster_funcs/test_gradients_at_links.py, landlab/grid/tests/test_raster_grid/test_init.py
This may help address #886 and https://github.com/conda-forge/landlab-feedstock/pull/5
@mcflugen I don't know why those tests did not issue DeprecationWarnings in the `Landlab-feedstock` PR.
I don't know that this will fix the issue for sure, but I do know that using `pytest.deprecated_call()` is generally the right choice. 
Passes locally.
Assuming this passes and can be merged into `landlab\master`, I think what we need to do is:
=> Change all pytest.warns(DeprecationWarning) to pytest.deprecated_call():

landlab/grid/hex.py
Fixes incorrect grid._boundary_nodes array for rect-shaped hex grids (issue #880) by adding a line to the function that sets up rect-hex boundary status.
=> fix issue 880: update _boundary_nodes in hex boundary setter

landlab/bmi/bmi_bridge.py, landlab/components/flow_accum/flow_accumulator.py, setup.py
This pull request adds boundary conditions (*status_at_node*) to the BMI wrapping of landlab components. When a landlab component is wrapped to expose a BMI, a new input/output var is added to the BMI component called "boundary_condition_flag", which is an interface to the landlab component's *status_at_node* field. Since BMI doesn't have any special way of representing boundary conditions, it must be done through BMI variables.
@kbarnhart , I made one other small change. In wrapping the *FlowAccumulator*, I noticed that the *flow__nodes_not_in_stack* field was never used. Because the field was never created, this caused problems for the wrapping. Anyway, I removed it from the class metadata (*_output_var_names* etc.). What do you think?
=> Add boundary conditions to BMI

landlab/bmi/bmi_bridge.py
This pull request fixes an error in wrapping landlab components that use *corners*. That is, any component that has fields defined at *corners*, *faces*, or *cells*. Unfortunately, *landlab* grids don't have a *corner_x* (or *x_of_corner*) attribute so the BMI wrapping process fails when trying to get, for example, the grid origin for the dual graph. To fix this, I just use `node_x[0] + 0.5 * dx` for the origin. This is definitely not an ideal fix but it will have to do until, probably, landlab 2.0.
There is another small fix that solves a problem when trying to figure out what "update" method to call on a BMI-wrapped component (i.e. *update()* vs. *run_one_step()* vs. *run_one_step(dt)*). This is also not an ideal fix but will also have to do until landlab 2.0, me thinks.
@kbarnhart If …
=> Fix BMI for corner_x/y of dual graphs

appveyor.yml
This pull request fixes #953. The problem seemed to arise from running `conda update conda` multiple times, which, for some reason, caused *setuptools* to be removed. In any case, I've cleaned up the build process so that it looks more like what we do on Travis and things seem to now be building on AppVeyor.
=> Fix issue 953

landlab/components/erosion_deposition/cfuncs.pyx, landlab/components/erosion_deposition/erosion_deposition.py, landlab/components/erosion_deposition/generalized_erosion_deposition.py, landlab/components/erosion_deposition/tests/test_erodep.py, landlab/components/erosion_deposition/tests/test_erodep_steady_state.py, landlab/components/erosion_deposition/tests/test_general_erodep.py, landlab/components/space/cfuncs.pyx, landlab/components/space/space.py, landlab/components/space/tests/test_space.py
* remove porosity from qs calculation
* finish deleting porosity from qs calc
* fix porosity in bed change equations in space
* fix porosity in bed change term in ed
* give defaults for space and ED, make positional arguments for generalized ED
* fixing analytical solutions in tests
* fix additional analytical solution bugs in tests
* fix TL analytical soln for erodep tests
* fix lint errors
* get rid of if in dt_max [skip ci]
* get rid of if in dt_min in erodep [skip ci]
* test negative ff and phi errors [skip ci]
* test to force timestep subdividing
* fix minimum calc
* temporarily deleting large dt test
* fix min/max error
* use python max instead of numpy
* fix mistake in space dt calc
* make dt calc cleaner
* fix lint errors [skip ci]
* add test to force timestep subdividing
* fix …
=> fix: Treatment of porosity in ErosionDeposition and SPACE fixed

landlab/bmi/bmi_bridge.py, landlab/ca/hex_cts.py, landlab/ca/tests/test_celllab_cts.py, landlab/components/fracture_grid/fracture_grid.py, landlab/components/fracture_grid/tests/test_fracture_grid.py, landlab/utils/__init__.py, landlab/utils/decorators.py, landlab/utils/return_array.py, landlab/utils/tests/test_return_grid.py
Add a return_array_at_link function, as a complement to the existing return_array_at_node. Also put both in __init__ so they're visible to landlab.utils, and catch an exception in one of the decorators.
=> add return_array_at_link

landlab/components/chi_index/channel_chi.py, landlab/components/groundwater/__init__.py, landlab/components/groundwater/dupuit_percolator.py, landlab/components/groundwater/tests/test_dupuit_percolator.py, landlab/data_record/data_record.py, landlab/data_record/tests/test_data_record_2dim.py, landlab/data_record/tests/test_data_record_item.py, landlab/data_record/tests/test_data_record_time.py, landlab/grid/tests/test_hex_grid/test_shape_dep_warning.py, landlab/grid/tests/test_raster_funcs/test_line_to_grid_coords.py
As part of the discussion regarding #909, and other needs of @pfeiffea and I with regard to the network sediment transporter, I'm replacing the now closed #948 with two PRs. This is the first of them. 
It changes DataRecord to not inherit from an Xarray Dataset. 
@margauxmouchene what do you think? 
I believe this will minimally impact ClastTracker, but please correct me if I am mistaken.
=> fix: change datarecord to not inherit from Xarray Dataset

landlab/data_record/data_record.py
we just started to get some errors about ordered dicts on `v2_dev`. @mcflugen fixed this earlier, but it would be nice to separate from the deprecation PR.
=> fix: ordered dict

landlab/components/groundwater/dupuit_percolator.py, landlab/components/groundwater/tests/test_dupuit_percolator.py
Fixes a missing sign in the gw velocity equations, adds support for locations where regolith thickness goes to zero, and ensures that the model produces a radially symmetric water table when aquifer base is radially symmetric and recharge is uniform over the domain.
=> Fix bug in GroundwaterDupuitPercolator, add symmetry test

.travis.yml, landlab/data_record/data_record.py
As discussed in the call this afternoon, we presently don't verify that code that will go into a release version of landlab works against the release version of the tutorials repo. 
This PR (which aims to pull into `release` intentionally) is to fix that. 
The travis script will probably need some fixing... but its probably pretty close to right. 
As written it makes a tutorials stage on the **continuous-integration/travis-ci/pr** CI builds.
=> Add tutorials stage to travis build

appveyor.yml, docs/source/user_guide/grid.rst, docs/source/user_guide/landlab_one_to_two.rst, landlab/components/chi_index/channel_chi.py, landlab/components/depression_finder/lake_mapper.py, landlab/components/diffusion/diffusion.py, landlab/components/flow_accum/flow_accumulator.py, landlab/components/flow_accum/lossy_flow_accumulator.py, landlab/components/flow_director/flow_director.py, landlab/components/gflex/flexure.py, landlab/components/lateral_erosion/lateral_erosion.py, landlab/components/sink_fill/fill_sinks.py, landlab/components/sink_fill/sink_fill_barnes.py, landlab/components/steepness_index/channel_steepness.py, landlab/field/graph_field.py, landlab/field/grouped.py, landlab/field/scalar_data_fields.py, landlab/grid/divergence.py, landlab/grid/gradients.py, landlab/io/netcdf/read.py, landlab/utils/distance_to_divide.py, landlab/utils/flow__distance.py, tests/field/test_graph_fields.py, tests/field/test_grouped_fields.py, tests/utils/test_flow__distance.py
This pull request fixes #979 by changing the `noclobber` keyword to `clobber` for methods that add fields to a grid. The `noclobber` keyword was confusing when using the double negative,`noclobber=False`.
=> Change noclobber keyword to clobber

landlab/components/groundwater/dupuit_percolator.py, landlab/components/groundwater/tests/test_dupuit_percolator.py
Fixes a missing sign in the gw velocity equations, adds support for locations where regolith thickness goes to zero, and ensures that the model produces a radially symmetric water table when aquifer base is radially symmetric and recharge is uniform over the domain.
=> Fix bug in GroundwaterDupuitPercolator, add symmetry test - take 2

landlab/bmi/bmi_bridge.py
This pull request fixes the `get_var_units` method of the bmi wrapper to use the new component metadata (i.e. `_info[name]["units"]` rather then `_var_units`)
=> Fix bmi get_var_units

landlab/components/profiler/base_profiler.py
@nathanlyons I realized that it would benefit the component tutorial (and similar uses) to be able to set a single color for a plot of the channel profiler (it can be repeatedly called, and the color can represent time). 
Its a small change @nathanlyons let me know if you think it's OK. 
I've made the change in the tutorials repo as well.
=> feat: add new way to set a color

docs/source/index.rst
Add a sentence pointing to the online webinar video to the 2nd paragraph of the introduction on the readthedocs landing page.
=> add link to webinar in doc header

.gitignore
JOSS submissions may include figures set to be ignored. This PR removes figure file types from gitignore.
=> remove gitignore image types for joss dir

.travis.yml, appveyor.yml
This pull request addresses issue #1109 as described by @kbarnhart. That is, we don't build/test/deploy (to PyPI) with Python 3.8.
=> Add Python 3.8 builds to AppVeyor and Travis

docs/source/install/index.rst
The pip update instructions were wrong (and didn't include the --pre channel). I realized this because of @rclavera's comment over on #1118 . This PR fixes it. I tested as best I could (made a new conda environment).
@mcflugen OK with you if we make a new release so we can have 3.8 builds? I think it would be v2.0.0b4
=> Fix pip update instructions

README.rst, docs/source/index.rst, setup.py
Addresses comments raised in #1125.
@mcflugen might you take a look.  I'm not sure if there are additional things we need to test in adding `python_requires`.
=> Improve clarity of dropping Py27 support

landlab/components/depth_dependent_diffusion/hillslope_depth_dependent_linear_flux.py, landlab/components/depth_dependent_taylor_soil_creep/hillslope_depth_dependent_taylor_flux.py
It was recently pointed out that the DepthDependentDiffuser and DepthDependentTaylorDiffuser docstrings reflect incorrectly the equations used by these components. 
This PR fixes this. 
It also cleans up the init to use the initialized_output_fields function.
=> Fix DepthDependentDiffuser and DepthDependentTaylorDiffuser docstrings

landlab/components/stream_power/stream_power_smooth_threshold.py
@gregtucker I found this while updating terrainbento to LL2. 
self._thresholds is an at-node array, so it needs to be indexed here.
=> StreamPowerSmoothThresholdEroder indexing bug

landlab/components/erosion_deposition/erosion_deposition.py, landlab/components/space/space.py, landlab/components/stream_power/fastscape_stream_power.py, landlab/components/stream_power/stream_power.py, landlab/components/stream_power/stream_power_smooth_threshold.py
This PR adds setters for the fluvial erodibility coefficient in 
- FastscapeStreamPower (and by extension StreamPowerSmoothThresholdEroder)
- StreamPowerEroder
- ErosionDeposition
- Space
These are necessary to support updating terrainbento to be compliant with LL2.
=> feat: add setters for erodibility for some stream power like components

README.rst
This should fix #1134. The problem was that, *readme_renderer*, which *PyPI* uses to render readme files as HTML, had a problem with duplicate target names for some of our external links and so it wouldn't render our README. We had multiple targets named *here* with text that looked like,
```rst
for more information click `here <some-link>`_.
```
To me, this seems like a bug in *readme_renderer* but, whatever the case, I've made changes to the README that remove the duplicate targets. I've run *readme_renderer* over this modified README and it passes.
=> Remove duplicate target names in README

.ci/travis/build_wheels.sh
This pull request attempts to fix #1139. I believe the only issue was that`.ci/travis/build_wheels.sh` specified only Python 3.6 and 3.7. With this pull request I've added `/opt/python/cp38-cp38/bin` to the list of Python versions to build.
I didn't add something like build everything that matches `/opt/python/*/bin` because the Docker image we're using includes Python 2.7, 3.4, and 3.5 (in addition to 3.6, 3.7, and 3.8).
=> Add Python 3.8 to Linux builds to send to PyPI

docs/source/conf.py, landlab/layers/eventlayers.py, notebooks/test_notebooks.py, tests/layers/test_event_layers.py
This pull request adds a new method, *reduce*, to *EventLayers*. The *reduce* method combines blocks of *EventLayers* into single blocks. So, for instance, if there are 200 layers, calling *reduce* could reduce the number of layers to 20 but averaging every 10 layers into a single layer. This can be useful when running a model that generates a large number of layers but only the most recently deposited layers are of importance and deeper layers can be archived to save memory.
As a demonstration of how this could be used, the following is a code snippet from the *Sequence* model,
```python
if (self.grid.event_layers.number_of_layers - self._n_archived_layers) % 20 == 0:
self.grid.event_layers.reduce(
self._n_archived_layers,
self._n_archived_layers + 10,
age=np.max,
percent_sand=np.mean, …
```
=> Add layer reducer

landlab/data_record/data_record.py
A bug in the DataRecord ffill_grid_element_and_id function resulted in this function occasionally backfilling values. 
Not surprisingly the amazing @pfeiffea found the bug. 
I fixed it.
=> fix: DataRecord forward fill bug

.ci/travis/build_wheels.sh
This pull request fixes creating *manylinux* builds for landlab on Travis using Docker. It seems the issue was that a new version of the *auditwheel* command now returns an error code (1) if it's given a non-platform wheel to repair. Since we just looped over all wheels in the *wheelhouse* folder, passing each one to *auditwheel*, *auditwheel* would return an error and the script would exit prematurely before creating further *manylinux* distributions.
To fix the problem, I simply allow *auditwheel* to return a non-zero code and continue with the loop.
=> Fix manylinux builds

landlab/io/netcdf/read.py, landlab/io/netcdf/write.py
The recent pull request #1029 slightly changed the treatment of "raster-netcdfs". These are netcdfs that write "x" and "y" as 1D data variables instead of as 2D variables. #1029 wrote raster netcdfs spatial information as 2D. Why did this happen... the tests in landlab weren't sufficient to distinguish the two types (but the tests in terrainbento are). 
This PR remedies the issue, adds a test, and adds some docs. 
With this terrainbento tests pass too!
=> Fix raster_netcdf format details

landlab/core/utils.py
@mcflugen without these extra two lines the tests can only pass once for me. otherwise the folder `methow` persists and the test fails with an error saying (smartly) that the folder is already there.
=> fix: remove fetched folder.

landlab/components/__init__.py, landlab/components/hand_calculator/__init__.py, landlab/components/hand_calculator/hand_calculator.py, tests/components/hand_calculator/test_hand.py
Addressing the need I described in #1204, this PR includes a new component that calculates the height of every node above the nearest drainage node (the union of nodes specified with a channel mask and open boundary nodes).
=> Add HeightAboveDrainageCalculator component

landlab/components/groundwater/dupuit_percolator.py, setup.cfg, tests/components/groundwater/test_dupuit_percolator.py
In my work I've found it useful to be able to get some information about the  state of the groundwater model during the intermediate steps taken by the adaptive timestep solver. In particular I am  using grid info to determine transient runoff generation patterns and develop storage-discharge relationships.
Here I've added the option for a user to supply a function that is executed every substep of the adaptive timestep solver.  It could append to a list outside of the model instance, print soemthing, write to a file, etc. The function supplied should have two required arguments, the grid and the substep duration, which I think should be sufficiently general for almost anything you would want to do as far as analysis and testing. 
There is an example of how I'm using this in the component …
=> Add callback function to GroundwaterDupuitPercolator

requirements.txt, tests/io/netcdf/test_to_netcdf.py
The latest version of *xarray* (*v0.16*) is now able to write fields of type *uint8*. Previously, *xarray* would return a *RuntimeError* when writing variables of that type unless writing to *NETCDF4*. With *v0.16*, the variables are written without error but are written as *int8* (as before, this is only an issue with formats other than *NETCDF*).
This pull request updates the tests that assumed a *RuntimeError* would be raised.
=> Fix netcdf uint8 tests

landlab/components/overland_flow/generate_overland_flow_deAlmeida.py, notebooks/teaching/surface_water_hydrology_exercises/overland_flow_notebooks/hydrograph_class_notebook.ipynb
Addresses bug identified by @kxwhipple on #1227 
The notebook at: notebooks/notebooks/teaching/surface_water_hydrology_exercises/overland_flow_notebooks/hydrograph_class_notebook.ipynb
set rainfall as OverlandFlow.rainfall_intensity = value. 
But in the migration to v2 I made many variables private, including rainfall intensity. 
This meant that the command in the notebook set a variable that was no longer used (OverlandFlow.rainfall_intesity rather than OverlandFlow._rainfall_intensity). Maybe there should be a test for this (since the notebook tests just enforce that they run without errors.... 
This PR makes a setter for this value, and enforces that the value should be zero or positive.  
Tagging @nicgaspar @jadams15 @gregtucker @mcflugen 
Also noting that the ESPIN is happening right …
=> Fix OverlandFlow notebook bug

docs/source/user_guide/grid.rst, landlab/components/flow_accum/flow_accumulator.py
Was looking at the documentation for landlab and came across a few things that didn't seem quite right. 
1. In the `grid` [section of the user guide](https://landlab.readthedocs.io/en/master/user_guide/grid.html#adding-data-to-a-landlab-grid-element-using-fields) several `=` signs were displayed as `-`. The `add_field` function was shown with the inputs `value_array` and `at='node'` flipped. Also when written as `clobber=False` this would not work if the previous code block defining the field 'elevation' with 0s has been run. 
2. In the [FlowAccumulator documentation](https://landlab.readthedocs.io/en/master/reference/components/flow_accum.html#landlab.components.flow_accum.flow_accumulator.FlowAccumulator) it looked like one of the example code blocks from the docstring didn't render. I …
=> Fix doc bugs

docs/source/reference/io/index.rst, docs/source/reference/io/obj.rst, landlab/io/__init__.py, landlab/io/obj.py, tests/io/test_write_obj.py
Simple utility to write a Landlab grid and 1 field (default `topographic__elevation`) to a Wavefront OBJ file, for import into visualization programs like Blender.
=> add Wavefront OBJ output

.github/workflows/test.yml, landlab/bmi/bmi_bridge.py, requirements.txt
This pull request adds Python 3.9 (and drops Python 3.6) from our testing. To get this to work, I had to make a small change to landlab's bmi wrapper so that we could use the latest *bmipy*. Previously we had been requiring *bmipy<2*, which wasn't available for Python 3.9.
=> Build and test landlab with Python 3.9

.github/workflows/black.yml, .github/workflows/docs.yml, .github/workflows/flake8.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/test-notebooks.yml, .github/workflows/test.yml, notebooks/test_notebooks.py
This pull request adds actions for publishing landlab releases to PyPI and prereleases TestPyPI. The release action is run if a tag is pushed that looks like *v.X.Y.Z* and the preprelease action is run if the tag looks like *vX.Y.XbN*. In both cases, a source distribution and wheels for all the platforms and Python 3.[789] will be built and uploaded.
=> Add release and prerelease github actions

tests/components/test_components.py
This pull request fixes a bug when testing a *landlab* component that has a missing *at_grid* field that is expected—by way of the *_info* attribute—to be something other than an *int*. Before this fix, if a component was missing a field, a new field—of type *int*—was added to the component and as a result, if some other type was expected an exception was raised. I've changed it so that now the new field is created with the type specified in *_info*.
I also cleaned up the component tests. All I really did was break up the single large test into smaller targeted tests where each test just tests one thing.
=> Fix bug when adding a missing at_grid field

.landscape.yaml, Makefile, README.rst, docs/source/development/install/index.rst, docs/source/development/install/install.rst, docs/source/development/install/installing_windows_compiler.rst, docs/source/development/install/troubleshooting_install.rst, docs/source/install/rough_guide_to_python.rst, docs/source/user_guide/faq.rst
This PR contains minor updates to the README and documentation 📝 . In particular, it changes the developer install instructions to use `pip install -e .` instead of `python setup.py develop` to ensure that Cython is called.
Also:
* Removed landscape.io
* Updated targets on Actions badges
* Made minor edits to README text 
This fixes #1271.
=> Update install instructions

.github/workflows/docs.yml, .github/workflows/test-notebooks.yml, .github/workflows/test.yml, docs/source/conf.py, docs/source/user_guide/components.rst, landlab/components/detachment_ltd_erosion/generate_erosion_by_depth_slope.py
This pull request is intended to fix #1334. In the move from Travis to GitHub Actions for our CI, we turned off *linkcheck* when testing our documentation build. It may be we had a good reason for doing so but I've turned it back on here to see if we can get it to work again.
=> docs: add linkcheck to docs testing

docs/source/conf.py, docs/source/index.rst, docs/source/reference/components/overland_flow.rst, docs/source/user_guide/faq.rst, docs/source/user_guide/field_definitions.rst, landlab/components/__init__.py, landlab/components/depth_dependent_diffusion/hillslope_depth_dependent_linear_flux.py, landlab/components/depth_dependent_taylor_soil_creep/hillslope_depth_dependent_taylor_flux.py, landlab/components/detachment_ltd_erosion/generate_erosion_by_depth_slope.py, landlab/components/overland_flow/__init__.py, landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py, landlab/components/overland_flow/kinematic_wave_rengers.py, notebooks/tutorials/hillslope_geomorphology/depth_dependent_taylor_diffuser/depth_dependent_taylor_diffuser.ipynb
In 2016 KinematicWaveRengers got deleted. This PR brings it back. 
I did all the things necessary to bring it in LL2.0 compliance (field names, private variables, use of super(), etc).
I brought it and two other missing kinematic wave components into the documentation.
I did a few other things to clean up existing issues that I observed when I built the docs. 
The existing test passes. 
tag: @frengers
=> Add KinematicWaveRengers back to components

environment-dev.yml, environment.yml
This pull request fixes the error found by @slundell123 and described in #1330. Newer versions of *pip* do not like it when we refer to requirements files with a *file:* prefix followed by a relative path (as we do in our *conda* environment files). We should, instead, either use a relative path name without the prefix or use the prefix followed by an absolute path. Since using absolute paths doesn't make sense, I've changed our environment files to use relative paths.
=> bld: drop "file:" prefix for pip requirements files

.pre-commit-config.yaml, requirements-dev.txt
This pull request simply adds a *.pre-commit-config.yaml* file for installing  [pre-commit](https://pre-commit.com/) hooks when developing with *landlab*. Once installed, *pre-commit* will run both *black* and *flake8* before every commit. This is in response to #1324 and closes #1332.
=> dev: add a pre-commit configuration file

landlab/components/soil_moisture/infiltrate_soil_green_ampt.py
This pull request fixes the docstring for *SoilInfiltrationGreenAmpt* by removing a non-standard heading that caused an error building the docs.
=> docs: fix unexpected section in green ampt component

.github/workflows/prerelease.yml, .github/workflows/release.yml
This is a small pull request that fixes how our *prerelease* and *release* workflows build our source distributions. Because our *setup.py* imports *numpy*, we must install *numpy* before running `python setup.py sdist`.
=> fix the building of source distributions for release workflows

.github/workflows/docs.yml, .github/workflows/test-notebooks.yml, .github/workflows/test.yml, README.rst, docs/source/development/install/install.rst, landlab/components/priority_flood_flow_router/priority_flood_flow_router.py, notebooks/exclude.yml, notebooks/test_notebooks.py, requirements-notebooks.txt, requirements.txt, setup.py, tests/components/priority_flood_flow_router/test_priority_flood_flow_router.py
This pull request allows *landlab* to be installed even if the *richdem* package is not available, which, for now, means leaving out *richdem* for Python 3.10 on Windows. Users will be able to use the entirety of *landlab* except for the *PriorityFloodFlowRouter*.
We, ultimately, will want to fix *richdem* to work on all of *landlab*'s supported platforms but this acts as a workaround until that time.
=> fix: install with richdem even if it is not available

.github/workflows/test-notebooks.yml, requirements-notebooks.txt
This pull request adds the OPENTOPOGRAPHY_API_KEY to the notebook testing so that a notebook is able to download data from OpenTopography using the *bmi-topography* package.
=> Add OPENTOPOGRAPHY_API_KEY to notebook tests

CHANGES.rst, docs/source/development/contribution/index.rst, news/.gitignore, news/1284.component, news/1292.feature, news/1356.bugfix, news/1358.feature, news/1360.feature, news/1370.feature, news/1379.bugfix, news/1383.component, news/1384.misc, news/1385.misc, news/1396.docs, pyproject.toml
This pull request sets up *[towncrier](https://towncrier.readthedocs.io/en/actual-freaking-docs/)* for updating and organizing our changelog.
@gregtucker, @mdpiper could one or both of you have a look at this and let me know what you think?
I've set *landlab* up to use the *towncrier* utility to, hopefully, help maintain a better CHANGELOG that our users (and we) can look at to quickly see all of the great new changes. The basic idea is that when someone submits a pull request they must create one or more files in the *news/* folder (with the name `<issue/pr #>.<pr type>`; e.g. `3142.bugfix`). We can then use *towncrier* to gather these news fragments and add them to our changelog. I've added some documentation about [how to create news …
=> Setup towncrier

news/1401.misc, tests/graph/hex/test_hex.py, tests/grid/test_create.py, tests/grid/test_create_network.py, tests/values/test_synthetic.py
Addresses #1401 by removing per-function *hypothesis* settings that turn off timing deadlines. Instead, timings deadlines are turned off globally when running continuous integration tests using Github Actions.
=> Remove per function hypothesis deadline setting

news/1410.misc, notebooks/tutorials/flow_direction_and_accumulation/PriorityFlood_realDEMs.ipynb, notebooks/tutorials/network_sediment_transporter/run_network_generator_OpenTopoDEM.ipynb
This pull request is an attempt to fix the continuous integration errors we are seeing for the notebook tests on *osx*. The failing tests are those for notebooks that use *bmi-topography* to download DEMs from OpenTopography. The reported error indicates that we haven't provided an API key, but that's not the case. In addition, the notebooks run just fine locally but the problem only arises when run through Github Actions.
=> Fix notebook ci errors on osx

requirements.txt, tests/io/shapefile/test_read_shapefile.py
This pull request fixes some failing unit tests caused by a new version of *pyshp*. With *pyshp* version 2.3.0, *shapefile.Writer* closes open streams, which makes those streams inaccessible after the writer completes, causing tests that continue to use these streams to fail. This error is described in GeospatialPython/pyshp#244.
For now I've just limited *pyshp* versions to anything other than 2.3.0.
=> Fix read_shapefile unit tests caused by closed BytesIO streams

README.rst, news/1419.docs
This pull request fixes the broken links to the openearthscape JupyterHub as described in #1419.
@mdpiper Does this fix the issue? Are these the appropriate links?
=> Update links to the new jupyterhub on lab.openearthscape

landlab/plot/__init__.py, landlab/plot/graph.py, news/1425.feature, news/1425.feature.1, news/1425.feature.2, news/1428.bugfix, news/1428.bugfix.1, tests/plot/test_graph.py
This pull request addresses the feature request described in #1425 as well as a few other bits. In particular,
* The *with_id* keyword now accepts a comma-separated list of grid elements (in the same way as for the *at* keyword) to include ids for.
* Patches and cells are filled in.
* Fixed a bug where -1 values were not being ignored in *corners_at_cell* and *nodes_at_patch*. This caused patches/cells with fewer links/faces than the maximum to include the last node/corner as part of their element
=> Enhance *plot_graph* following #1425

landlab/grid/base.py, landlab/grid/raster.py, landlab/plot/__init__.py, landlab/plot/event_handler.py, landlab/plot/imshow.py, landlab/plot/imshowhs.py, news/1424.feature, news/1430.feature, notebooks/tutorials/boundary_conds/set_BCs_from_xy.ipynb, notebooks/tutorials/boundary_conds/set_BCs_on_raster_perimeter.ipynb, notebooks/tutorials/boundary_conds/set_BCs_on_voronoi.ipynb, notebooks/tutorials/boundary_conds/set_watershed_BCs_raster.ipynb, notebooks/tutorials/ecohydrology/cellular_automaton_vegetation_DEM/cellular_automaton_vegetation_DEM.ipynb, notebooks/tutorials/ecohydrology/cellular_automaton_vegetation_flat_surface/cellular_automaton_vegetation_flat_domain.ipynb, notebooks/tutorials/flexure/lots_of_loads.ipynb, notebooks/tutorials/lithology/lithology_and_litholayers.ipynb, notebooks/tutorials/marine_sediment_transport/simple_submarine_diffuser_tutorial.ipynb, notebooks/tutorials/plotting/landlab-plotting.ipynb, notebooks/tutorials/reading_dem_into_landlab/reading_dem_into_landlab.ipynb, tests/plot/test_imshow_grid.py
This pull request addresses #1424 but adding an *at* keyword to *imshow* when used as a *ModelGrid* method. There are also a couple other changes:
* *imshow* is now available to all *ModelGrids*
* *imshow* can now guess at a location to plot values if the *at* keyword is not given. This allows things like: `grid.imshow(values)` and `grid.imshow("topographic__elevation")`.
* deprecates the *values_at* keyword
* deprecates usages like `imshow("node", "topographic__elevation")`
=> Add "at" keyword for imshow and other enhancements

landlab/components/gravel_river_transporter/gravel_river_transporter.py, news/1445.bugfix, pyproject.toml, tests/components/gravel_river_transporter/test_gravel_river_transporter.py
This pull request addresses conda-forge/landlab-feedstock#48. I've modified *pyproject.toml* to only include *landlab* ~and exclude the *tests* folder. This is overkill as just including `landlab*` would work just fine—no need to also exclude `tests*`.~
=> Exclude tests folder from installed packages

notebooks/exclude.yml
This pull request excludes the failing notebook, *run_network_generator_OpenTopoDEM.ipynb* from our testing (see #1447).
=> Exclude the failing opentopography notebook from testing

.github/workflows/changelog.yml, CHANGES.rst, docs/source/conf.py, news/1433.misc, news/1439.component, news/1439.notebook, news/1442.bugfix, news/1444.bugfix, news/1446.misc, pyproject.toml, requirements-docs.txt
This pull request:
* adds a GitHub Actions workflow that checks if a pull request contains a news fragment
* adds missing news fragments for some recent pull requests.
It looks like the following issues/pull requests are missing news fragments,
=> Add CI check for news fragments

news/1480.misc, pyproject.toml, requirements-docs.txt
This pull request fixes #1480 by limiting *towncrier* to versions less than 22.8. The next release of *sphinxcontrib.towncrier* should fix this, at which point the changes in this pull request should be undone.
=> Fix #1480; limit towncrier version to less than v22.8

.github/dependabot.yml, .github/workflows/rebase_dependencies.yml, news/1602.misc
This pull request changes the target branch for _dependabot_ pull requests from *master* to *dependencies*. I've also added a GitHub action workflow that will automatically rebase the _dependencies_ branch whenever _master_ is changed.
=> Change the target branch for dependabot pull requests

landlab/components/network_sediment_transporter/bed_parcel_initializers.py, landlab/components/network_sediment_transporter/sediment_pulser_at_links.py, landlab/components/network_sediment_transporter/sediment_pulser_each_parcel.py, news/1722.feature, news/1722.misc, news/1722.misc.1, notebooks/tutorials/network_sediment_transporter/sediment_pulser_at_links.ipynb, tests/components/lateral_erosion/test_latero.py, tests/components/network_sediment_transporter/test_bed_initializer.py, tests/components/network_sediment_transporter/test_sediment_pulser.py
This pull request fixes the flaky tests described in #1722.
The ``LateralEroder`` test (`test_ss_sed_flux`) was would occasionally fail because the initial elevation grid was created with some random noise but without using a seed. I rewrote the test to use an initial seed with `np.random.default_rng`.
The `sediment_pulser_at_links.ipynb` notebook that would occasionally stall had a similar problem—several of the `NetworkSedimentTransporter` utilities used a random number generator but not an initial seed. Certain sets of random numbers generated a configuration that would stall the notebook. To fix this, I've added an `rng` keyword to these functions/classes that allow a user to pass a random number generator, a seed, or `None` for the old behavior.
=> Fix flaky LateralEroder and NetworkSedimentTransporter tests

.github/workflows/docs.yml, .github/workflows/test-notebooks.yml, .github/workflows/test.yml, news/1754.bugfix, noxfile.py, requirements-testing.in, tests/components/lateral_erosion/test_latero.py
This pull request fixes our builds that began failing when *conda* added Python 3.12 as the default version. Note that I've done this by disabling Python 3.12 builds. I'm not sure one can build *Landlab* within a Python 3.12 environment yet. That, I hope, will come shortly with a subsequent pull request.
It appears, at least for the time being, some of *Landlab*'s dependencies might not be available for Python 3.12, which is now the default Python for *conda*. Because of this, some of our CI builds were failing while trying to create a testing environment. To fix this, I've specified Python versions (3.11, for now) in all of our *nox* sessions that use the *mamba* backend. Then, for the ci builds, I use the ``--force-pythons`` option to force *nox* to create a new environment with the …
=> Fix CI builds for Python 3.12

news/1850.misc, noxfile.py
This pull request fixes an issue with installing the *multidict* package on Mac and Python 3.12 when using the *conda* compilers. Since *multidict* does not yet provide a wheel for python 3.12 on [PyPI](https://pypi.org/project/multidict/), it must be built from source, which requires compiling some C code. That C code, though, requires *clang* 14 (not 16, which is the latest *conda-forge* version).
The temporary fix is to modify the *test* and *test-notebooks* *nox* sessions to install *multidict* from *conda-forge* if using Python 3.12 on Mac. Once Python 3.12 wheels are available for *multidict*, these changes should be removed.
The error we were seeing when running our CI tests was the following (the entire error message is pasted at the end),
``` …
```
=> Fix an issue installing multidict on Mac and Python 3.12

.pre-commit-config.yaml
This pull request excludes *flake8-bugbear* v24.4.21, which seems to have a bug that causes many false positives for B909 (``editing a loop's mutable iterable often leads to unexpected results/bugs``).
See https://github.com/PyCQA/flake8-bugbear/issues/467.
=> Exclude buggy flake8-bugbear version that reports B909 false positives

landlab/field/graph_field.py, landlab/graph/graph.py, landlab/graph/voronoi/voronoi_to_graph.py, landlab/grid/base.py, landlab/io/netcdf/dump.py, landlab/io/netcdf/write.py, landlab/plot/network_sediment_transporter/plot_network_and_parcels.py, news/1910.misc, tests/data_record/test_data_record_2dim.py, tests/data_record/test_data_record_item.py, tests/data_record/test_data_record_time.py, tests/graph/voronoi/test_voronoi_to_graph.py, tests/io/netcdf/test_to_netcdf.py, tests/plot/network_sediment_transporter/test_plot_network_and_parcels.py
This pull request fixes #1910. I've just replaced usages of `Dataset.dims` with `Dataset.sizes`.
=> Fix FutureWarning caused by usage of xarray.Dataset.dims

src/landlab/core/model_component.py, src/landlab/grid/hex.py, src/landlab/grid/raster.py, src/landlab/plot/imshow.py, src/landlab/plot/imshowhs.py, src/landlab/values/synthetic.py
Upgrades core landlab to use the `at` keyword with field methods.
ref: #1999
=> Upgrade deprecated field methods in core landlab

conftest.py, news/2018.bugfix, src/landlab/__init__.py
As reported in #2018, if *landlab* is used with an older version of *numpy*, an error is raised when trying to print a *numpy* array. This is due to us calling *numpy*'s `set_printoptions` function within `__init__.py` using the `legacy` keyword, which isn't available for older versions of *numpy*. This was done solely to ensure correct array formatting of the *doctests* and, otherwise, didn't have anything to do with the proper functioning of *landlab*.
I've removed the offending line from `__init__.py` and added a test fixture that calls `set_printoptions` so that it's only run with the tests.
=> Fix numpy printoptions

docs/source/conf.py, news/1986.misc, src/landlab/plot/network_sediment_transporter/plot_network_and_parcels.py
See issue #1986 
@Ashaniekam wants to be able to use `plot_network_and_parcels` in a straightforward way on top of `imshowgrid` (or similar), but it wasn't cooperating. I made two minor edits to bring `plot_network_and_parcels` into alignment with the other plotting tools: 
1. `plot_network_and_parcels` now has options for output, same as `imshowgrid` (used to automatically plot inline right away)
2. when you pass it an existing figure (e.g. DEM created via `imshowgrid`) via the `fig=` keyword argument, `plot_network_and_parcels` will plot the network on the same axes as the existing figure axes. 
Warning: I did not take into account making space for other preexisting fig items like colorbars or legends associated with the figure (e.g. DEM) that is being added to. So... if you find …
=> Fix plot network and parcels

docs/source/tutorials/index.md
I was checking the tutorial and found those two typos, just two words, so I'm not adding all the description, checklist, etc
=> Typos fixed in index.md

src/landlab/components/network_sediment_transporter/network_sediment_transporter.py, tests/components/network_sediment_transporter/test_init.py
Reading through the code of NetworkSedimentTransporter, I came across code that uses `ValueError` in checking function arguments. `ValueError` is documented as follows:
> Raised when an operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as [IndexError](https://docs.python.org/3/library/exceptions.html#IndexError).
In the three cases changed here, it is that the argument has the wrong *type*, not an invalid value. The right exception class for this is `TypeError`, documented as
> Raised when an operation or function is applied to an object of inappropriate type. The associated value is a string giving details about the type mismatch.
> [...]
> Passing arguments of the wrong type …
=> Use TypeError instead of ValueError.

docs/source/tutorials/output/writing_legacy_vtk_files.ipynb, noxfile.py
=> Fix broken link to vtk formats

news/2207.bugfix, src/landlab/io/esri_ascii.py, tests/io/test_esri_ascii.py
=> Fix esri_ascii lower left corner/center

news/2204.feature, src/landlab/io/esri_ascii.py, tests/io/test_esri_ascii.py
=> Add nodata_value keyword to esrii_ascii.dump function

news/2177.misc, src/landlab/components/profiler/channel_profiler.py, tests/components/profiler/test_channel_profile.py
=> Improve error messages for invalid watersheds in ChannelProfiler

docs/source/conf.py
=> Fix linkcheck errors for csdms.colorado.edu
