landlab/landlab

- landlab/testing/tools.py
Fixed small bugs, add doctests for `cd` and `cdtemp` functions.
> Minor bug fixes to landlab.testing.tools

- landlab/utils/structured_grid.py
Import tested functions into doctests to fix `NameError` errors.
> Fixed doctests

- landlab/io/netcdf/tests/test_write_netcdf.py
Added a couple unit tests for writing grids that have `unit8` and `int64` fields.
> Added tests for uint8 and int64 types.

- appveyor.yml
- landlab/components/cellular_automata/celllab_cts.py
This pull request adds Slack notifications for AppVeyor. AppVeyor build and test results will be sent to the **#testing** channel of the landlabdev Slack group.
> Add appveyor notifications to Slack

- landlab/components/flow_routing/route_flow_dn.py
- landlab/components/stream_power/examples/drive_sp_params_voronoi.txt
- landlab/components/stream_power/examples/simple_sp_driver.py
- landlab/components/stream_power/examples/test_voronoi_sp.py
- landlab/grid/base.py
- landlab/grid/raster.py
- landlab/plot/imshow.py
The flow_router is now modified to work with the optional argument
method=‘D4’. Defaults to D8.
Also, a couple of helper grid properties for go with d8 routing.
> Voronoi stream power

- landlab/components/flow_routing/lake_mapper.py
- landlab/components/flow_routing/tests/test_lake_mapper.py
- landlab/components/sink_fill/fill_sinks.py
- landlab/components/sink_fill/tests/test_sink_filler.py
- landlab/testing/tools.py
New component fills pits in a starting topography, exploiting the lake_mapper for a lot of the donkey work.
Fill can either be flat, or sloping gently towards the outlet. Method is clever enough to handle simple terrain where "back flow" is needed to get parts of the flat connected up to the outlet, but it remains to be seen how it performs on real topographies (and, dare I say, LiDAR??)
Bunch of tests here confirm things are 100% robust on simple topographies, though I suspect there might be some interesting use cases lurking out there in the wild where lakes get big and topos get highly irregular.
> sink_fill component

- appveyor.yml
This pull request attempts to fix our Python 2.7 build errors on AppVeyor.
> Fix Python 2.7 builds on AppVeyor

- docs/index.rst
- docs/landlab.grid.rst
A rough draft. Highest order categories (5 of them) in place. Have some questions about the next level down and if the files are auto-generated or if I should edit away. Greg is going to clean up the docs directory a bit first.
> new toc for index.rst

- docs/conf.py
- docs/dev_guide_components.rst
- docs/index.rst
- docs/landlab.ca.boundaries.rst
- docs/landlab.ca.rst
- docs/landlab.components.rst
- docs/landlab.components.sink_fill.rst
- docs/landlab.grid.rst
- landlab/io/netcdf/write.py
change grid api docs to reflect file structure
this is a draft of a new grid organization, feedback welcome
subsequent sections to follow
> updated index.rst, landlab.grid.rst, and landlab.ca

- landlab/ca/boundaries/hex_lattice_tectonicizer.py
- landlab/ca/celllab_cts.py
- landlab/ca/examples/turbulent_suspension_with_settling_and_bleaching.py
- landlab/ca/hex_cts.py
- landlab/ca/landlab_ca.py
- landlab/ca/oriented_hex_cts.py
- landlab/ca/oriented_raster_cts.py
- landlab/ca/raster_cts.py
- landlab/components/fire_generator/generate_fire.py
- landlab/components/flow_routing/flow_routing_D8.py
- landlab/components/flow_routing/lake_mapper.py
- landlab/components/glacier_thin_ice_model/glacier.py
- landlab/components/overland_flow/generate_overland_flow_deAlmeida.py
- landlab/components/sink_fill/fill_sinks.py
- landlab/core/model_parameter_dictionary.py
- landlab/grid/hex.py
- landlab/grid/radial.py
- landlab/grid/raster.py
- landlab/grid/structured_quad/rectilinear.py
- landlab/grid/structured_quad/structured.py
- landlab/grid/unstructured/base.py
- landlab/grid/unstructured/cells.py
- landlab/grid/unstructured/links.py
- landlab/grid/unstructured/nodes.py
- landlab/grid/voronoi.py
- landlab/plot/video_out.py
- landlab/utils/decorators.py
- landlab/utils/fault_facet_finder.py
- landlab/utils/jaggedarray.py
- landlab/utils/jaggedarray_ma.py
> Jk copy init docstring

- docs/index.rst
- docs/landlab.grid.base.rst
- docs/landlab.grid.create.rst
- docs/landlab.grid.decorators.rst
- docs/landlab.grid.gradients.rst
- docs/landlab.grid.hex.rst
- docs/landlab.grid.mappers.rst
- docs/landlab.grid.radial.rst
- docs/landlab.grid.raster.rst
- docs/landlab.grid.raster_aspect.rst
- docs/landlab.grid.raster_funcs.rst
- docs/landlab.grid.raster_gradients.rst
- docs/landlab.grid.raster_mappers.rst
- docs/landlab.grid.raster_set_status.rst
- docs/landlab.grid.raster_steepest_descent.rst
- docs/landlab.grid.voronoi.rst
- landlab/grid/raster.py
- landlab/grid/tests/test_raster_grid/test_fixed_link_boundary.py
new structure to break up the rst files so they more closely match the landlab core repo
> Jk rearrange index

- docs/index.rst
- docs/landlab.bmi.rst
- docs/landlab.ca.tests.rst
- docs/landlab.cmd.rst
- docs/landlab.components.chi_index.rst
- docs/landlab.components.diffusion.tests.rst
- docs/landlab.components.flow_routing.tests.rst
- docs/landlab.components.fracture_grid.tests.rst
- docs/landlab.components.nonlinear_diffusion.tests.rst
- docs/landlab.components.overland_flow.tests.rst
- docs/landlab.components.potentiality_flowrouting.tests.rst
- docs/landlab.components.sink_fill.tests.rst
- docs/landlab.components.steepness_index.rst
- docs/landlab.components.stream_power.tests.rst
- docs/landlab.components.transport_limited_fluvial.tests.rst
- docs/landlab.core.tests.rst
- docs/landlab.grid.gradients.rst
- docs/landlab.grid.raster_gradients.rst
- docs/landlab.grid.rst
- docs/landlab.grid.tests.testing_hex_grid.rst
- landlab/grid/base.py
- landlab/grid/gradients.py
- landlab/grid/mappers.py
- landlab/grid/raster_gradients.py
- landlab/grid/raster_mappers.py
- landlab/grid/raster_steepest_descent.py
> Jk cleanup grid docs

- landlab/grid/base.py
- landlab/grid/divergence.py
Adds modernized flux-divergence and net flux functions, for:
* faces => cells
* links => nodes
* faces => nodes
> Gt flux divergence

- landlab/components/diffusion/diffusion.py
> fix diffusion.py g / qs issue

- landlab/components/diffusion/diffusion.py
- landlab/components/flow_routing/flow_routing_D8.py
- landlab/core/utils.py
- landlab/grid/base.py
- landlab/grid/divergence.py
- landlab/grid/gradients.py
- landlab/grid/raster.py
- landlab/grid/raster_aspect.py
- landlab/grid/raster_funcs.py
- landlab/grid/raster_gradients.py
- landlab/grid/tests/test_raster_funcs/test_gradients_at_active_links.py
- landlab/grid/tests/test_raster_funcs/test_gradients_at_links.py
- landlab/grid/tests/test_raster_funcs/test_node_id_of_adjacent.py
- landlab/grid/tests/test_raster_grid/test_patches.py
This is ready for a quick look
> Change of's to at's

- landlab/plot/imshow.py
enhance some functionality; ensure other functionality is available for
both grid types.
(Sorry this guy is late for v1.0! Would be good to have for next week though)
> thorough debug of imshow tools

- docs/index.rst
- docs/landlab.components.detachment_ltd_erosion.rst
- docs/landlab.core.utils.rst
- docs/landlab.grid.raster.rst
- docs/landlab.plot.rst
- docs/landlab.utils.decorators.rst
> Finish revising index.rst

- landlab/ca/celllab_cts.py
- landlab/ca/cfuncs.pyx
- landlab/ca/oriented_hex_cts.py
- landlab/ca/oriented_raster_cts.py
- setup.py
Assuming the tests pass, I'd like to merge this. @mcflugen, you have the most experience with cython -- could you take a look?
> Gt cythonize cts

- landlab/grid/hex.py
- landlab/grid/voronoi.py
This PR simply adds a new method nodes_at_column() to HexModelGrid, and replaces some string comparisons with character comparisons. @mcflugen, could you take a quick look please?
> Gt add fn to hex

- .conda-recipe/meta.yaml
- docs/compilers_in_windows.rst
- landlab/__init__.py
> Revert "SiccarPoint/patch flowaccum reclimit"

- landlab/components/flow_accum/flow_accum_bw.py
- landlab/components/flow_routing/flow_direction_DN.py
- landlab/components/flow_routing/lake_mapper.py
- landlab/components/flow_routing/route_flow_dn.py
Didn't succeed in fixing the bug, which is that the lake mapper skips a whole chunk of drainage basin in one particularly large DEM. I can't reproduce the error except on this enormous DEM, which is too big to effectively debug. If anyone else experiences the lake mapper missing a chunk of their (smaller!) terrain, please reawaken this issue.
> Gt lake routing bug

- landlab/components/__init__.py
- landlab/components/cubic_nonlinear_hillslope_flux/__init__.py
- landlab/components/cubic_nonlinear_hillslope_flux/cubic_nonlinear_hillslope_flux.py
- landlab/components/weathering/exponential_weathering.py
This resolves a couple of conflicts and merges Rachel's wonderful new Cubic Nonlinear Diffusion component
> Gt merge rg cubic

- landlab/components/__init__.py
- landlab/components/cubic_nonlinear_hillslope_flux/cubic_nonlinear_hillslope_flux.py
Corrects a typo in __init__.py in components
> fix typo in components/init

- landlab/components/cubic_nonlinear_hillslope_flux/cubic_nonlinear_hillslope_flux.py
Nothing major, just changed name of "k" to "soil_transport_coefficient", and did some PEP8 formatting.
> edits cubic diff (just var names and PEP8)

- landlab/field/scalar_data_fields.py
- landlab/field/tests/test_grouped_fields.py
- landlab/grid/tests/test_raster_grid/test_fields.py
Changes data field class to permit n-d arrays at grid locations. 
Adds a new unit test.
> Make nd fields

- landlab/components/stream_power/sed_flux_dep_incision.py
Should resolve GT’s issue #429
> move paren

- landlab/components/stream_power/stream_power.py
Also cleaned up some warnings about unused imports and an assigned but unused var, plus deleted some old commented-out lines.
@SiccarPoint can you review and merge? Should be a quick and easy one
> stream_power.py: minor fix to avoid array-string comparison

- landlab/components/__init__.py
- landlab/components/depth_dependent_cubic_soil_creep/__init__.py
- landlab/components/depth_dependent_cubic_soil_creep/hillslope_depth_dependent_cubic_flux.py
- landlab/components/depth_dependent_cubic_soil_creep/tests/solution_for_4x7_grid_steady_state.ipynb
- landlab/components/depth_dependent_cubic_soil_creep/tests/test_depth_dependent_cubic_diffuser.py
This component combines features of Rachel's depth-dependent LINEAR diffuser and (not depth dependent) cubic diffuser. It includes a unit test against an analytical solution, which is worked out in a Jupyter notebook in the tests folder.
> Gt create depth dep cubic diffuser

- landlab/components/hybrid_alluvium/hybrid_alluvium.py
Class variables now point to grid fields in init so grid fields don't need to be updated at the end of run_one_step.
> streamlined grid field pointers, more comments

- landlab/components/__init__.py
- landlab/components/hybrid_alluvium/__init__.py
- landlab/components/hybrid_alluvium/hybrid_alluvium.py
made/edited __init__ files for Hybrid Alluvium component @kbarnhart
> inits for Hybrid Alluvium

- landlab/components/hybrid_alluvium/hybrid_alluvium.py
fixed a problem where discharge was calculated in __init__ and never updated. Now it is calculated in run_one_step.
> area changes now result in q changes

- landlab/components/hybrid_alluvium/cfuncs.pyx
- landlab/components/hybrid_alluvium/hybrid_alluvium.py
- setup.py
This makes the hybrid alluvium component faster and addresses issue #493. 
This commit also changes an error in the hydrology routines:
discharge_method should have been self.discharge_method and area_method should have been self.area_method
@cmshobe please add tests that use each of these different hydrology routines and provide area and discharge methods in all of the possible forms (str, none, etc).
> Cythonize the qs_in routine

- landlab/components/stream_power/cfuncs.pyx
- landlab/components/stream_power/stream_power_smooth_threshold.py
> Cythonized stream power smooth threshold.

- landlab/components/flow_accum/flow_accumulator.py
This means flow accumulation only occurs once and speeds up running the lake mapper/flow accumulator combination.
> Run the lake mapper before flow accumulator. 

- landlab/components/erosion_deposition/cfuncs.pyx
- landlab/components/erosion_deposition/erosion_deposition.py
- landlab/components/erosion_deposition/tests/test_erodep_steady_state.py
Some edits to the ErosionDeposition component to make it interoperable with Erosion Modeling Suite
> Gt edit erodep

- landlab/components/cubic_nonlinear_hillslope_flux/cubic_nonlinear_hillslope_flux.py
- landlab/components/cubic_nonlinear_hillslope_flux/tests/test_cubic_nonlinear_hillslope_flux.py
- landlab/components/depth_dependent_cubic_soil_creep/hillslope_depth_dependent_cubic_flux.py
- landlab/components/depth_dependent_cubic_soil_creep/tests/test_depth_dependent_cubic_diffuser.py
This implements a dynamic time-stepper in the component CubicNonLinearDiffuser that is similar to the one implemented in DepthDependentCubicDiffuser.
This addresses Issue #518. This PR is similar to the PR that addressed Issue #496.
> Dynamic timestep option for CubicNonLinearDiffuser

- landlab/components/erosion_deposition/erosion_deposition.py
Addresses #522 
@gregtucker @cmshobe let me know if you have comments.
> Fixing ErosionDeposition so that it can handle negative slopes with n<1

- landlab/components/erosion_deposition/erosion_deposition.py
> Address Issue #527 

- landlab/components/cubic_nonlinear_hillslope_flux/cubic_nonlinear_hillslope_flux.py
- landlab/components/cubic_nonlinear_hillslope_flux/tests/test_cubic_nonlinear_hillslope_flux.py
> Address Issue #549  CubicNonlinearDiffuser __init__ kwargs

- docs/index.rst
- docs/landlab.components.transport_length_diffusion.rst.txt
- landlab/components/__init__.py
- landlab/components/transport_length_diffusion/__init__.py
- landlab/components/transport_length_diffusion/tests/test_tl_hill_diff.py
- landlab/components/transport_length_diffusion/transport_length_hillslope_diffusion.py
Hillslope diffusion component inspired by transport length-model equations by Carretier et al (2016) and Davy & Lague (2009)
> Transport-length-model hillslope diffuser

- landlab/components/flow_director/flow_direction_DN.py
This pull request removes some old and unused code from the `flow_directions` function. This old code was replaced by cython code that ran faster and so was no longer used.
> Remove unused code from flow_direction_DN

- landlab/components/soil_moisture/infiltrate_soil_green_ampt.py
This pull request fixes a bug in the `SoilInfiltrationGreenAmpt` component that caused negative infiltration for small water depths. I've also done some tidying up.
> Fix bug in Green-Ampt

- landlab/components/depth_dependent_diffusion/hillslope_depth_dependent_linear_flux.py
- landlab/components/depth_dependent_taylor_soil_creep/hillslope_depth_dependent_taylor_flux.py
This PR addresses Issue #600. It covers both the DepthDependentDiffuser and the TaylorDepthDependentDiffuser. 
@Glader011235 @gregtucker can you check it out and see if it fixes the problems you are having. 
If it does I'll address failing tests and and create any necessary new ones.
> Address depth dependent boundary conditions

- landlab/components/stream_power/stream_power.py
> Fixes type checking issue

- landlab/plot/imshow.py
very small fix related to an inconsistent name.
> A name that is inconsistent between text and function definition

- landlab/components/normal_fault/normal_fault.py
> Addressing NormalFault kwargs

- landlab/ca/boundaries/hex_lattice_tectonicizer.py
- landlab/ca/cfuncs.pyx
Update tracking of particle IDs ("propswap") in hex_lattice_tectonicizer
> Repair CellLab's HexLatticeTectonicizer to handle property tracking during vertical uplift

- landlab/components/space/space.py
Addresses Issue #668 
Tagging @cmshobe for review as well. 
Also, @cmshobe could you make some tests to demonstrate that the various methods of instantiating all work?
> SPACE: switching type testing to instance

- docs/index.rst
- docs/landlab.components.normal_fault.rst
> Adding NormalFault to the sphinx documentation

- landlab/components/erosion_deposition/erosion_deposition.py
- landlab/components/space/space.py
Addresses #660 
Tagging @cmshobe
> Space rounding

- landlab/graph/graph.py
> adding >>> graph.adjacent_nodes_at_node  so that values print.

- landlab/components/erosion_deposition/cfuncs.pyx
- landlab/components/erosion_deposition/erosion_deposition.py
- landlab/components/space/cfuncs.pyx
- landlab/components/space/space.py
addresses Issues #717 and #718 
Tagging @cmshobe  as well. 
As part of the main space overhaul we plan to make more comprehensive  tests
> Fix cell area and porosity in Space and Erosion Deposition

- landlab/components/erosion_deposition/generalized_erosion_deposition.py
- landlab/components/erosion_deposition/tests/test_erodep.py
- landlab/components/erosion_deposition/tests/test_general_erodep.py
- landlab/components/space/tests/test_space.py
@kbarnhart @gregtucker I have:
-finished all the tests in SPACE, E/D, and the generalized E/D base class that @kbarnhart suggested.
-filled out the parameters documentation in the` __init__` of the generalized E/D base class.
> additional testing for SPACE, E/D, and generalized E/D base class

- CHANGELOG.md
- scripts/make_changelog.py
This pull request adds a script that creates a changelog from the git history of pull requests into master. To use,
```bash
$ ./scripts/make_changelog.py > CHANGELOG.md
```
Changes are grouped into sections for each release (tags), and changes within each group are divided into the subsections: *Added*, *Deprecated*, *Removed*, *Fixed*, *Security*, and *Changed*. Changes are put into each of these subsections based on the first word in the commit message of the merge. So, for example, if the merge message was "Added the cool new function, *do_stuff*" it would be listed under to the *Added* section.
Note that for this to work well, when merging a pull request, the one-line description should changed from the default message to something more descriptive and that follows this convention.
> Add script to create a nicely formatted changelog

- landlab/components/flow_accum/flow_accumulator.py
> Replace try/except with if

- landlab/plot/imshow.py
> changing to set_facecolor

- docs/landlab.components.spatial_precip.rst
This resolves a stupid typo in the SpatialPrecipitationDist docs…
> Missing word

- landlab/plot/imshow.py
> setting image default to be a raster

- landlab/utils/decorators.py
Addresses #812 
Passes tests locally (OSX/py3.6)
> Fix argspec warnings

- landlab/components/spatial_disturbance/spatial_disturbance.py
Added susceptibility for fires.
> Saisiddu add runon sm susc 20aug18

- .conda-recipe/meta.yaml
- appveyor.yml
- landlab/ca/tests/test_celllab_cts.py
- landlab/components/drainage_density/tests/test_drainage_density.py
- landlab/components/flow_accum/flow_accum_bw.py
- landlab/components/flow_accum/flow_accum_to_n.py
- landlab/components/flow_accum/flow_accumulator.py
- landlab/components/flow_accum/tests/test_flow_accums.py
- landlab/components/pet/tests/conftest.py
- landlab/framework/collections.py
- landlab/io/shapefile/read_shapefile.py
- landlab/io/shapefile/tests/test_read_shapefile.py
- landlab/plot/channel_profile.py
- landlab/plot/drainage_plot.py
- setup.py
> Address unexpected network model grid error

- landlab/io/esri_ascii.py
- landlab/io/netcdf/read.py
- landlab/utils/__init__.py
- landlab/utils/add_halo.py
- landlab/utils/tests/test_halo.py
> Add halo and add-to-grid for netcdf

- landlab/components/flow_accum/cfuncs.pyx
- landlab/components/flow_accum/flow_accum_bw.py
- landlab/components/flow_accum/flow_accum_to_n.py
This PR addresses #892.
FYI @nicgaspar @nathanlyons
> Cythonize parts of flow routing

- landlab/components/overland_flow/generate_overland_flow_deAlmeida.py
> modify docs

- landlab/core/utils.py
> add degree to radian function

- landlab/bmi/bmi_bridge.py
- landlab/components/overland_flow/generate_overland_flow_deAlmeida.py
- landlab/components/soil_moisture/soil_moisture_dynamics.py
- landlab/components/transport_length_diffusion/transport_length_hillslope_diffusion.py
- landlab/values/synthetic.py
This pull request makes some necessary changes to get our BMI wrapping working. The main thing to notice is that all of the BMI methods are now implemented. I've also had to make some minor tweaks to a few components - typos in the metadata, `update` method shouldn't have any required arguments.
I've also made a change to the `synthetic.constant` function. Because not all fields will be *float*, I've added a *dtype* keyword so that a user can set the data type of the created array. If *dtype* is not provided, it is determined from the type of the *value* keyword (i.e. 1.0 means *float*, 1 means *int*).
@kbarnhart Would you please have a look at this? It should be quick.
> Implement BMI methods

- landlab/components/depth_dependent_diffusion/hillslope_depth_dependent_linear_flux.py
- landlab/components/depth_dependent_taylor_soil_creep/hillslope_depth_dependent_taylor_flux.py
- landlab/components/depth_dependent_taylor_soil_creep/tests/solution_for_4x7_grid_steady_state.ipynb
- landlab/components/depth_dependent_taylor_soil_creep/tests/test_depth_dependent_taylor_diffuser.py
Modified both regular and taylor depth dependent hillslope components to correctly incorporate soil transport decay depth, as per issue #935. Also added tests for expected decay depth behavior.
> Depth dependent 6 5 2019

- docs/landlab.components.fracture_grid.rst
- landlab/components/__init__.py
- landlab/components/fracture_grid/__init__.py
- landlab/components/fracture_grid/fracture_grid.py
- landlab/components/fracture_grid/tests/test_fracture_grid.py
This accomplishes #966 on v2dev.
> feat: make fracture grid a component (FractureGridGenerator) (#966)

- landlab/utils/__init__.py
- landlab/utils/decorators.py
- landlab/utils/return_array.py
- landlab/utils/tests/test_return_grid.py
Implements #943 by @gregtucker on `v2_dev`.
> feat: add return_array_at_link

- landlab/components/chi_index/channel_chi.py
This PR permits one to pass a noclobber argument to the ChiFinder. Addresses #976 and necessary for a project I am working one. 
@SiccarPoint I think you are the original author, LMK if this is OK with you.
> feat:add no clobber to ChiFinder

- landlab/components/chi_index/channel_chi.py
> feat:add no clobber to ChiFinder (#977)

- landlab/utils/distance_to_divide.py
- landlab/utils/tests/test_distance_from_divide.py
In #918 I added a hack calculator and a distance to the divide function to `v2_dev`.
For a variety of reasons, it would be nice to have the distance to the divide function in `master`. This PR does that.
> feat: add distance to divide

- landlab/components/__init__.py
- landlab/components/groundwater/__init__.py
- landlab/components/groundwater/dupuit_percolator.py
- landlab/components/groundwater/tests/test_dupuit_percolator.py
- landlab/data_record/data_record.py
- landlab/data_record/tests/test_data_record_2dim.py
- landlab/data_record/tests/test_data_record_item.py
- landlab/data_record/tests/test_data_record_time.py
This PR brings PR #989 onto v2_dev
> fix: PR 989

- docs/index.rst
- docs/landlab.data_record.data_record.rst
* docs for DataRecord
Edits necessary to build documentation for DataRecord
* Rename landlab.date_record.data_record.rst to landlab.data_record.data_record.rst
> PR #857 docs for DataRecord 

- landlab/components/__init__.py
- landlab/components/lateral_erosion/__init__.py
- landlab/components/lateral_erosion/lateral_erosion.py
- landlab/components/lateral_erosion/node_finder.py
- landlab/components/lateral_erosion/tests/test_latero.py
> feat: add LateralEroder to v2_dev

- landlab/data_record/data_record.py
- landlab/data_record/tests/test_data_record_2dim.py
- landlab/data_record/tests/test_data_record_item.py
- landlab/data_record/tests/test_data_record_time.py
- landlab/data_record/tests/test_dummy.py
- landlab/data_record/tests/test_errors.py
Equivalent of #990 on `v2_dev`.
> feat: add dummy capability to data record

- landlab/__init__.py
- landlab/_registry.py
- landlab/cmd/landlab.py
- landlab/grid/create.py
- landlab/grid/hex.py
- landlab/grid/mappers.py
- landlab/grid/radial.py
- landlab/grid/raster.py
- landlab/grid/raster_mappers.py
- versioneer.py
These escaped an earlier attempt to remove all things py2.x related
> fix: remove calls to __future__

- landlab/components/groundwater/dupuit_percolator.py
- tests/components/groundwater/test_dupuit_percolator.py
brings @DavidLitwin 's improvements to the GroundwaterDupuit Percolator into the landlab 2.0 development branch
> feat: Add seepage to GroundwaterDupuitPercolator  (#1007)

- landlab/components/weathering/exponential_weathering.py
Clarifying the docstring of the ExponentialWeatherer, as per issue #1010.
> Clarify ExponentialWeatherer docstring

- environment-dev.yml
- setup.py
@mcflugen on a previous PR for 2.0 I had removed the dependencies in `setup.py` from the `environment-dev.yml` file. 
This PR fixes this by putting them back.
> fix: add all dependencies to env file

- .travis.yml
* add tutorials stage to travis build
* fix doctest that assumes Dataset.attrs is OrderedDict
* get into the right directory.
* install additional dependencies
> Add tutorials stage to travis build (#1022)

- landlab/components/chi_index/channel_chi.py
- landlab/components/depression_finder/lake_mapper.py
- landlab/components/groundwater/dupuit_percolator.py
- landlab/components/lateral_erosion/lateral_erosion.py
- landlab/components/profiler/profiler.py
- landlab/field/scalar_data_fields.py
- tests/components/groundwater/test_dupuit_percolator.py
- tests/components/profiler/test_profiler.py
* Handle zero permeable thickness
* no permeable thickness in adaptive timestep solver
* Bug fix: sign in velocity calculation
* Add water table symmetry test
* delint
* Small changes to syntax, add K setter
* Delint
> Fix bug in GroundwaterDupuitPercolator, add symmetry test

- docs/landlab.components.taylor_nonlinear_hillslope_flux.rst
- landlab/components/taylor_nonlinear_hillslope_flux/taylor_nonlinear_hillslope_flux.py
Some minor tweaks to the documentation of this component, to make it easier to follow.
> SiccarPoint/refine Taylor diffn docs

- docs/source/development/practices/dev_guide_releases.rst
- docs/source/reference/components/taylor_nonlinear_hillslope_flux.rst
- landlab/components/depth_dependent_diffusion/hillslope_depth_dependent_linear_flux.py
- landlab/components/depth_dependent_taylor_soil_creep/hillslope_depth_dependent_taylor_flux.py
- landlab/components/groundwater/dupuit_percolator.py
- landlab/components/taylor_nonlinear_hillslope_flux/taylor_nonlinear_hillslope_flux.py
- tests/components/taylor_nonlinear_hillslope_flux/test_taylor_nonlinear_hillslope_flux.py
This implements #1034 on v2_dev. 
Also a very small number of typos that I've noticed.
> Refine Taylor docs and also a few typos

- landlab/components/overland_flow/generate_overland_flow_kinwave.py
found while getting tutorials to run.
> Small fix to kinwave overland flow

- docs/source/development/contribution/develop_a_component.rst
- docs/source/user_guide/tutorials.rst
- landlab/components/lithology/Readme.md
Few hyperlinks not changed in #1052
> straggling v2_dev binder references

- docs/source/install/index.rst
Add add'l installation instructions.
> docs: add new 2.0 installation instructions for conda

- docs/source/development/install/updating.rst
> update docs about updating

- notebooks/tutorials/transport-length_hillslope_diffuser/TLHDiff_tutorial.ipynb
On of a number of things to do for #1082 .
> Reduce time of transport length diffusion tutorial by making grid smaller

- joss/species_evolver/paper.bib
> Bibtex fix

- README.rst
- docs/source/development/index.rst
- landlab/components/groundwater/readme.md
@DavidLitwin I think this should do for addressing #1108.
Let me know what you think.
> Add'l doc and readme updates

- README.rst
- docs/source/index.rst
- docs/source/install/index.rst
- docs/source/user_guide/tutorials.rst
PR addresses #1157.
Also minor suggestions to main index.rst, mostly header formatting and doc outline order.
> notebook launch docs

- landlab/components/groundwater/dupuit_percolator.py
Set hydraulic conductivity in run_one_step methods when that wasn't necessary.
> fix bug created in #1168

- .travis.yml
- landlab/components/erosion_deposition/cfuncs.pyx
- landlab/components/flexure/cfuncs.pyx
- landlab/components/flow_director/cfuncs.pyx
- landlab/components/space/cfuncs.pyx
- landlab/components/stream_power/cfuncs.pyx
- landlab/graph/hex/ext/hex.pyx
- landlab/graph/sort/ext/remap_element.pyx
- landlab/graph/sort/ext/spoke_sort.pyx
- landlab/grid/cfuncs.pyx
- landlab/grid/structured_quad/cfuncs.pyx
- requirements-docs.txt
The URL to the *Miniconda* download changed a couple weeks ago, which caused our CI on Travis to fail (since we use *Miniconda* to install Python). This pull request fixes the URL.
> Fix URL for miniconda download

- docs/source/development/install/index.rst
- docs/source/development/install/installing_windows_compiler.rst
- docs/source/install/index.rst
> Update windows install instructions

- docs/source/reference/components/hand_calculator.rst
- docs/source/reference/components/index.rst
I made a .rst file for the hand_calculator, and added it to the component documentation index.
> Add docs links for hand model

- docs/source/user_guide/papers_presentations.rst
Updates the list in the documentation. No changes to code.
> update list of papers and presentations

- joss/in_preparation/network_sediment_transporter/paper.md
- joss/in_preparation/network_sediment_transporter/papers.bib
A few changes to the JOSS paper .md and .bib files (for reference formatting, primarily), also fixing @mcflugen's affiliation. 
fyi: @pfeiffea
> Small NST Joss paper fixes

- docs/source/user_guide/papers_presentations.rst
Update publications list in documentation.
> add two 2020 publications

- docs/source/reference/components/flow_accum.rst
- docs/source/reference/components/flow_director.rst
- landlab/components/flow_accum/flow_accum_to_n.py
> add flow accum docs

- landlab/components/depression_finder/cfuncs.pyx
- landlab/io/__init__.py
- tests/components/depression_finder/test_lake_mapper.py
Addresses #1219. I have some local fails related to netCDF which I suspect are known? New test passes fine.
> Siccar point/fix 1219

- notebooks/tutorials/river_input_lem/adding_discharge_point_source_to_a_lem.ipynb
Adds a tutorial showing how to add a discharge/area point source using the FlowAccumulator. Addresses  #1252.
> add tutorial for river input to LEMs

- docs/source/user_guide/papers_presentations.rst
Add references to papers_presentations.rst
> add additional references for 2020/21

- docs/source/index.rst
- docs/source/user_guide/clinics_workshops.rst
- environment-dev.yml
- landlab/__init__.py
- landlab/components/discharge_diffuser/diffuse_by_discharge.py
- landlab/components/tectonics/listric_kinematic_extender.py
- landlab/utils/fault_facet_finder.py
- tests/ca/test_celllab_cts.py
- tests/components/tectonics/test_listric_kinematic_extender.py
This PR is a collection of minor adjustments ("updates" is too strong a word) to the LL documentation, including modifications to:
- the LL 2.0 comment
- Python version support
- the list of clinics and workshops
- the LL v1 and v2 references
This PR also fixes #1289.
> Touch documentation

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- pyproject.toml
- setup.py
This pull requests attempts to use [cibuildwheel](https://github.com/pypa/cibuildwheel) for building *landlab* wheels.
> dev: use cibuildwheel for building wheels

- landlab/plot/__init__.py
- landlab/plot/layers.py
- news/1373.docs
- news/1398.feature
- notebooks/tutorials/carbonates/carbonate_producer.ipynb
- tests/plot/test_layers.py
This pull request adds a new function, *plot_layers*, that creates a stratigraphic plot of sediment layers.
> Add plot_layers function

- landlab/graph/framed_voronoi/dual_framed_voronoi.py
- landlab/graph/framed_voronoi/framed_voronoi.py
- landlab/grid/framed_voronoi.py
- news/1450b.misc
- news/1495.misc
- notebooks/tutorials/grid_object_demo/diverse_grid_classes.ipynb
- tests/grid/test_constructors.py
Amends FramedVoronoiGrid with general idea developed in #1450 and comments of #1454 on the seeds and edge node ids.
> Amend FramedVoronoiGrid issue #1450 #1454 follow-up

- docs/source/conf.py
- landlab/field/graph_field.py
- news/1500.misc
This pull request is meant to to address #1500 by adding a more descriptive error
message when trying to add a field to a grid that already contains a field with that name.
```python
>>> from landlab import RasterModelGrid
>>> grid = RasterModelGrid((3, 4), xy_spacing=10.0)
>>> grid.add_zeros("topographic__elevation", at="node")
>>> grid.add_zeros("topographic__elevation", at="node")
Traceback (most recent call last):
FieldError: Unable to add the field, 'topographic__elevation', to the group, 'node', because a field with that name already exists in that group. Use `clobber=True` to replace the existing field. For example: grid.add_field('topographic__elevation', at='node', clobber=True)
```
I've also removed some docstring lint from the `graph_field.py` module
and added *intersphinx* …
> Improve error message when adding an already-existing field

- USEDBY.rst
- news/1538.docs
> add recent pubs to list

- .github/workflows/test-notebooks.yml
- news/1539.misc
- noxfile.py
- pyproject.toml
- requirements-notebooks.txt
This pull request is an attempt to fix the failing notebook test described in #1539. At first it looked like it might be due to a recent *rasterio* release but using an older version didn't fix the problem. It appears, instead, that limiting the *bmi-topography* version to 0.8 or less fixes the issue.
@mdpiper Do you have an idea what might be going on here?
> Fix failing PriorityFlood_realDEMs notebook test (#1539)

- README.rst
- docs/source/getting_started/10min.rst
- docs/source/getting_started/teach_yourself_landlab.rst
- docs/source/user_guide/teaching_tutorials.rst
- docs/source/user_guide/tutorials.rst
- news/1556.bugfix
- news/1556.docs
- notebooks/tutorials/syllabus.ipynb
This PR adds links to run the Landlab example and teaching notebooks on the *lab* and *jupyter* instances of EarthscapeHub.
This fixes #1555 and fixes #1508.
> Add links to run notebooks on EarthscapeHub

- news/1644.misc
- noxfile.py
- requirements.in
> Fix missing hypothesis error when running notebook tests

- .github/workflows/test-notebooks.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- landlab/components/stream_power/cfuncs.pyx
- landlab/graph/cfuncs.pyx
- landlab/graph/sort/ext/argsort.pyx
- landlab/grid/ext/raster_divergence.pyx
- landlab/grid/ext/raster_gradient.pyx
- landlab/grid/raster_divergence.py
- landlab/grid/raster_gradients.py
- landlab/utils/decorators.py
- news/1639.misc
- noxfile.py
- pyproject.toml
- requirements-testing.in
- setup.py
- tests/grid/test_raster_divergence.py
- tests/grid/test_raster_gradients.py
This pull request is an attempt to migrate to Cython 3.
Highlights:
* Changed the build-system (in *pyproject.toml*) to use *cython* version 3.0.0b3 or greater. It seems to have some improvements we could use and, I believe, @sebastien-lenard  was wanting to use some of that new functionality in his new routing components.
* *cythonized* (and parallelized using *openmp*) functions that calculate gradients, and divergence on raster grids.
* Added some (speed) benchmarks for the new cythonized code.
* Added `-fopenmp` to the compile options. Note that this this is only added if the WITH_OPENMP environment variable is set. I did this because the default compilers on Mac and Windows do not come with *openmp*. To use *openmp* on Mac, I use the *conda* compilers (I imagine use Homebrew would …
> Migrate to Cython 3

- docs/requirements.in
- news/1696.docs
- pyproject.toml
- requirements.in
This pull request fixes an error that was causing the docs to not build with the following error,
```
Configuration error:
This documentation is not using `furo.css` as the stylesheet. If you have set `html_style` in your conf.py file, remove it.
```
We weren't setting `html_style` in our *config.py* file but we were, however, installing *sphinx_rtd_theme* as a requirement, which must have installed its own stylesheet (h/t https://github.com/pradyunsg/furo/discussions/299#discussioncomment-6768440).
> Fix documentation build error about furo.css stylesheet not being used

- .github/workflows/docs.yml
- .github/workflows/test-notebooks.yml
- .github/workflows/test.yml
- news/1703.misc
This pull request switches our CI for testing from *miniconda* to *micromamba*. It's probably something we should have already been doing but recent build errors seem to be fixed by the switch.
The errors we were seeing were things like,
```python
Traceback (most recent call last):
File "C:\Miniconda\envs\test\Scripts\mamba-script.py", line 6, in <module>
from mamba.mamba import main
File "C:\Miniconda\envs\test\Lib\site-packages\mamba\mamba.py", line 49, in <module>
import libmambapy as api
File "C:\Miniconda\envs\test\Lib\site-packages\libmambapy\__init__.py", line 7, in <module>
raise e
File "C:\Miniconda\envs\test\Lib\site-packages\libmambapy\__init__.py", line 4, in <module>
from libmambapy.bindings import *  # noqa: F401,F403
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load …
```
> Switch CI to use micromamba

- docs/source/install/developer_install.rst
- docs/source/installation.rst
- news/1654.bugfix
- news/1704.docs
This pull request updates the *conda*/*mamba* installation commands in the docs to explicitly include channels. Since some of *Landlab*'s dependencies are not available in the default *conda* channel, it's important to tell *conda* to look to *conda-forge* for packages (see #1704). If someone doesn't have *conda-forge* in their *.condarc* file, packages from *conda-forge* won't be seen and users will see a ``PackagesNotFoundError``.
As there can be incompatibilities with packages from the default channel and from *conda-forge*, it's good practice to ensure that all packages come from *conda-forge*. Thus, the install command now looks like,
```
conda install --file=requirements.in -c nodefaults -c conda-forge --override-channels
```
This tells conda to look at *conda-forge*, ignore the …
> Update install commands to include channels

- docs/requirements.txt
- notebooks/requirements.txt
- requirements.txt
This pull request bump *certifi*, which removes a security vulnerability.
> Bump certifi

- .readthedocs.yaml
- docs/requirements.in
- news/1722.misc
This pull request removes unused requirements for building the documentation. I've also removed the `htmlzip` format from the *readthedocs* builds since it's not supported by *furo* (it also took an extra few minutes to build).
> Clean up requirements to build the docs

- README.rst
- docs/source/development/contribution/develop_a_component.rst
- docs/source/getting_started/10min.rst
- docs/source/getting_started/teach_yourself_landlab.rst
- docs/source/user_guide/build_a_model.rst
- docs/source/user_guide/components.rst
- docs/source/user_guide/examples.rst
- docs/source/user_guide/faq.rst
- docs/source/user_guide/grid.rst
- docs/source/user_guide/python_numpy_intro.rst
- docs/source/user_guide/teaching_tutorials.rst
- docs/source/user_guide/tutorials.rst
- environment.yml
- news/1758.misc
This pull request addresses #1758, which describes an issue with running the tutorial notebooks (and the "10 minutes to *Landlab*" tutorial, in particular) on *Binder*.
The main problem was that the environment file used by *Binder* pointed to a non-existent requirements file (it was moved in a previous pull request some time ago). In addition to fixing the environment file, I've also updated the *Binder* links to point to the *master* branch of *Landlab*, which contains the up-to-date environment file.
> Fix environment file and Binder links

- .readthedocs.yaml
- news/1762.misc
This pull request updates the *readthedocs* configuration file to exclude the now invalid option, *system_packages*. Although #1730 also fixes this, that PR's not ready to go yet and this issue is preventing the docs from building.
> Update the readthedocs config file

- .pre-commit-config.yaml
- landlab/components/stream_power/cfuncs.pyx
- news/1763.misc
- pyproject.toml
This pull request updates the *isort* configuration in *pyproject.toml*. It seems that a newer version of *isort* began to identify *landlab* as a third party package and thus moved all *landlab* imports into the third-party section (along with e.g. *numpy*, and *scipy*). I've updated *pyproject.toml* to explicitly set *landlab* as a first-party package and, while I was at it, simplified *isort*'s configuration by using the *black* profile.
> Update the isort configuration

- .github/workflows/changelog.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/prerelease.yml
- .github/workflows/rebase_dependencies.yml
- .github/workflows/release.yml
- .github/workflows/test-notebooks.yml
- .github/workflows/test.yml
- docs/requirements.txt
- notebooks/requirements.txt
- requirements.txt
> Bump dependencies

- news/1794.misc
- tests/components/network_sediment_transporter/test_sediment_pulser.py
This pull request should fix the flaky tests of the ``SedimentPulser`` components. All I've done is added a random seed to each of the pulsers to ensure the tests are reproducible.
> Fix flaky sediment pulser tests

- .readthedocs.yaml
- news/1797.misc
This pull request fixes an issue that prevented the docs from building or *readthedocs.io*. I just needed to fix the path to the requirements file for the docs.
> Fix path to requirements file needed by readthedocs

- news/1915.misc
- setup.py
This pull request adds a list of all the extensions to be built to ``setup.py``. The downside of doing this is that this list must be manually updated when adding/removing extension modules but the upside is that it is more explicit and prevents unwanted extensions being found as in #1909.
> List all extensions in setup.py

- .github/workflows/test.yml
- .pre-commit-config.yaml
- landlab/_version.py
- news/1945.misc
- noxfile.py
- pyproject.toml
- requirements.in
This pull request limits *numpy* to less than 2.0. Building with *numpy* 2 results in the following error,
```
landlab/ca/cfuncs.pyx:27:9: 'int_t' is not a type identifier
```
I'll work on getting *Landlab* working with *numpy* 2 in another pull request.
> Require numpy to less than v2

- news/1996.misc
- notebooks/tutorials/agent_based_modeling/groundwater/landlab_mesa_groundwater_pumping.ipynb
- notebooks/tutorials/component_tutorial/component_tutorial.ipynb
- notebooks/tutorials/flexure/lots_of_loads.ipynb
- notebooks/tutorials/groundwater/groundwater_flow.ipynb
- notebooks/tutorials/hillslope_geomorphology/depth_dependent_taylor_diffuser/depth_dependent_taylor_diffuser.ipynb
- notebooks/tutorials/landscape_evolution/hylands/HyLandsTutorial.ipynb
- notebooks/tutorials/network_sediment_transporter/network_plotting_examples.ipynb
- notebooks/tutorials/network_sediment_transporter/network_sediment_transporter_NHDPlus_HR_network.ipynb
- notebooks/tutorials/overland_flow/kinwave_implicit/kinwave_implicit_overland_flow.ipynb
- notebooks/tutorials/overland_flow/overland_flow_erosion/ol_flow_erosion_components.ipynb
- notebooks/tutorials/overland_flow/soil_infiltration_green_ampt/infilt_green_ampt_with_overland_flow.ipynb
- notebooks/tutorials/visualization/blender/landlab_to_blender.ipynb
- notebooks/tutorials/visualization/paraview/importing_landlab_netcdf_to_paraview.ipynb
- noxfile.py
This pull request updates the *nbmake* markers we use for the notebook tests that label certain notebooks as "slow". The markers are now in their own namespace. The markers used to be in the notebooks' metadata as,
```json
"metadata": {
"execution": {
"markers": "slow"
}
}
```
but are now,
```json
"metadata": {
"execution": {
"nbmake": {
"markers": "slow"
}
}
}
```
> Update nbmake markers in notebook metadata

- src/landlab/components/chi_index/channel_chi.py
- src/landlab/components/depression_finder/lake_mapper.py
- src/landlab/components/depth_dependent_taylor_soil_creep/hillslope_depth_dependent_taylor_flux.py
- src/landlab/components/discharge_diffuser/diffuse_by_discharge.py
- src/landlab/components/flow_accum/lossy_flow_accumulator.py
- src/landlab/components/fracture_grid/fracture_grid.py
- src/landlab/components/lake_fill/lake_fill_barnes.py
- src/landlab/components/mass_wasting_runout/mass_wasting_runout.py
- src/landlab/components/overland_flow/generate_overland_flow_implicit_kinwave.py
- src/landlab/components/overland_flow/kinematic_wave_rengers.py
- src/landlab/components/potentiality_flowrouting/route_flow_by_boundary.py
- src/landlab/components/sink_fill/fill_sinks.py
- src/landlab/components/sink_fill/sink_fill_barnes.py
- src/landlab/components/spatial_precip/generate_spatial_precip.py
- src/landlab/components/steepness_index/channel_steepness.py
- src/landlab/components/stream_power/stream_power.py
Upgrades landlab components to use the `at` keyword with field methods.
ref: #1999
> Upgrade deprecated field methods in landlab components

- src/landlab/ca/boundaries/hex_lattice_tectonicizer.py
- src/landlab/ca/celllab_cts.py
- src/landlab/ca/hex_cts.py
- src/landlab/ca/oriented_hex_cts.py
- src/landlab/ca/oriented_raster_cts.py
- src/landlab/ca/raster_cts.py
- tests/ca/test_user_guide_example.py
- tests/components/depression_finder/test_lake_mapper.py
- tests/components/drainage_density/test_drainage_density.py
- tests/components/erosion_deposition/test_ero_dep_mass_conservation.py
- tests/components/erosion_deposition/test_ero_dep_with_flats.py
- tests/components/erosion_deposition/test_shared_with_flats.py
- tests/components/groundwater/test_dupuit_percolator.py
- tests/components/lake_fill/test_lake_fill.py
- tests/components/mass_wasting_runout/conftest.py
- tests/components/species_evolution/test_zone_objects.py
- tests/components/stream_power/test_not_implemented_errors.py
- tests/field/test_graph_fields.py
- tests/grid/test_create.py
- tests/grid/test_raster_grid/test_allocators.py
- tests/values/test_synthetic.py
Upgrades ``tests`` and ``landlab.ca`` to use the `at` keyword with field methods.
ref: #1999
> Upgrade deprecated field methods in tests, landlab.ca

- .credits.toml
- .mailmap
- AUTHORS.rst
- news/2005.misc
- src/landlab/cmd/authors.py
- src/landlab/cmd/landlab.py
This pull request make the start string that indicates the beginning of the credits list in the authors file configurable. This will be useful when switching between different markdown formats (for example from rst to myst).
I've also updated the list of contributors.
> Make the credits start string configurable

- USEDBY.rst
This pull request fixes links to DOIs and standardizes how we format the DOIs in the references.
> Fix DOI links in USEDBY

- .github/workflows/test.yml
- news/2012.misc
- noxfile.py
- pyproject.toml
- setup.py
This pull request modifies the *test* workflow so that the tested wheels are built using *cibuildwheel*. This is now the wheels are built for publishing on TestPyPI/PyPI so it is nice if we test the actual wheels that are being published.
I've also split the unit tests and the notebook tests into separate jobs. This way, since the docs job only needs the notebook-tests, the docs can begin building as soon as the notebook tests finish.
> Use cibuildwheel to build wheels in the test workflow

- docs/source/conf.py
- src/landlab/_version.py
This pull request prepares *Landlab* for the upcoming 2.9 release.
> Prepare for v2.9 release

- news/2015.bugfix
- src/landlab/utils/ext/jaggedarray.pyx
- tests/utils/test_jaggedarray.py
This pull request fixes an issue with unraveling a `jaggedarray` when the offset is an array of `int32`. This cropped up as an issue on Windows where `long` is 32 bits. See csdms/pymt#174. I hope this will also fix that issue.
The fix was to rewrite the *cython* to use fused types and allow for a wider range of data types.
> Fix an issue with unraveling jaggedarray on Windows

- news/1999.misc
- src/landlab/field/graph_field.py
When we moved from Landlab 0 to 1, we unofficially deprecated the passing of a field's location as the first parameter of many of the field methods, in favor of the `at` keyword. For example, instead of
```python
grid.add_ones("cell", "topographic__elevation")
```
we preferred using,
```python
grid.add_ones("topographic__elevation", at="cell")
```
In this pull request I've added a `FutureWarning` to these methods if they are called with the location as the first argument. I've also upgraded usage throughout *Landlab*.
> Upgrade old field method usage

- src/landlab/bmi/standard_names.py
A recent update to *flake8-bugbear* found new lint in `standard_names.py`. This pull request removes it.
> remove repeated key/value pair from standard name dictionary

- docs/requirements.in
- docs/source/conf.py
- news/2049.docs
- requirements/docs.txt
This pull request fixes and issue with the tabs in the citation section. The section uses tabs from the *sphinx-design* extension but that extension wasn't installed.
> Fix tabs in citation section

- docs/source/development/contribution/develop_a_component.md
- docs/source/user_guide/reference/components.md
- docs/source/user_guide/reference/grid.md
- docs/source/user_guide/reference/values.md
- news/2048.misc
This pull request removes unnecessary `toctree` directives from the docs. In the component and grid pages, there were a bunch of `toctree` sections that should have just been lists of cross-references. Even though *sphinx* complained about pages being referenced in multiple `toctree`s, the docs did still built but this cleans things up a bit.
> Remove unnecessary toctree directives from the docs

- docs/source/user_guide/grid_methods/01_nodes_links_patches.md
- docs/source/user_guide/grid_methods/02_corners_faces_cells.md
- docs/source/user_guide/grid_methods/03_boundary_conditions.md
- docs/source/user_guide/grid_methods/04_element_subsets.md
- docs/source/user_guide/grid_methods/05_element_mapping.md
- docs/source/user_guide/grid_methods/06_gradients.md
- docs/source/user_guide/grid_methods/07_surface_analysis.md
- docs/source/user_guide/grid_methods/99_uncategorized.md
- news/2052.misc
- src/landlab/bmi/bmi_bridge.py
- src/landlab/core/model_component.py
- src/landlab/core/utils.py
- src/landlab/grid/decorators.py
- src/landlab/grid/gradients.py
- src/landlab/grid/hex_mappers.py
- src/landlab/grid/mappers.py
- src/landlab/grid/raster_gradients.py
- src/landlab/grid/raster_mappers.py
- src/landlab/io/esri_ascii.py
- src/landlab/io/native_landlab.py
- src/landlab/io/netcdf/read.py
- src/landlab/io/netcdf/write.py
- src/landlab/io/obj.py
- src/landlab/plot/imshow.py
- src/landlab/plot/imshowhs.py
- src/landlab/utils/decorators.py
- src/landlab/utils/source_tracking_algorithm.py
This pull request removes the name of the current module for all *sphinx* `autosummary` directives. That is, replacing things like,
```
.. autosummary::
~landlab.io.esri_ascii.dump
```
with
```
.. autosummary::
~dump
```
New versions of *sphinx* doesn't like the former.
> Remove the current module from autosummary tables

- docs/requirements.in
- docs/source/conf.py
- requirements/docs.txt
This pull request updates the docs to work with *sphinx* v8.
> Update the docs for sphinx 8

- USEDBY.md
This is addresses #2103 by updating the `USEDBY.md`.
> Add new landlab references for Jan 2025

- .github/workflows/test.yml
- docs/source/conf.py
This pull request adds a job to our GitHub actions workflow that deploys the built documentation, which was built using the executed notebooks that are tested in a previous job, to [github pages](https://landlab.github.io/landlab). Our docs can still be found at *readthedocs* but will now have a banner that says those docs are just for testing and the official docs can be found at the new location.
If people like this, the only thing to do is decide when we want to deploy the new docs. We don't want to deploy on every commit (as is currently the case) but maybe with every commit to the *master* branch?
> Deploy docs with executed notebooks to GitHub pages

- .pre-commit-config.yaml
- docs/source/tutorials/making_components/making_components.ipynb
- src/landlab/graph/framed_voronoi/dual_framed_voronoi.py
- src/landlab/graph/framed_voronoi/framed_voronoi.py
- tests/components/profiler/test_profiler.py
- tests/graph/framed_voronoi/test_framed_voronoi.py
Our *pre-commit* hooks were a little old, so I bumped all of them to their latest versions. There was some newly-found lint, so I removed that as well.
> Bump pre-commit hooks to their latest versions

- .github/workflows/test.yml
- docs/source/conf.py
- news/2121.misc
- noxfile.py
I fixed a bunch of broken links in #2118 but would like to make sure they stay fixed. I've added a job to our CI workflow that runs a link checker on all of the links in our documentation. This includes links found in the documentation files, docstrings and the notebooks.
> Add a GitHub Actions workflow job to ensure there are no broken links

- .github/workflows/test.yml
- noxfile.py
Our *noxfile* was getting a little unwieldy and had some repeated code. I've tried to unwield it at bit by moving the repeated code into separate sections: *install* and *build*. The *install* session takes a single positional argument that points to either a wheel file or a folder that contains wheels. *pytest* options can no longer provided as positional arguments, instead one can use the `PYTEST_ADDOPTS` environment variable.
> Clean up the noxfile and add install session

- .github/workflows/test.yml
- news/2133.misc
- noxfile.py
- pyproject.toml
- requirements-testing.in
- requirements/testing.txt
I would like to try to use *codecov* for tracking our coverage rather than *coveralls*. I've tried using *codecov* elsewhere and I think it works well. It's easier to integrate into our GitHub Actions workflows and its web interface is better.
> Setup codecov for tracking coverage

- news/2087.misc
- requirements-testing.in
- requirements/testing.txt
- tests/components/flexure/test_flexure.py
- tests/conftest.py
- tests/data_record/test_aggregators.py
- tests/graph/quantity/test_of_element.py
- tests/graph/structured_quad/test_quad.py
- tests/grid/test_create_network.py
- tests/grid/test_raster_divergence.py
- tests/grid/test_raster_gradients.py
This pull request removes the benchmarks from the tests. These benchmarks will be moved into the *Landlab* benchmarking repository and run using *airspeed velocity*. Some of the benchmarks took a considerable time to run so I hope this will speed up our testing time.
> Remove benchmarks from the tests

- noxfile.py
When we switched to *codecov* (#2133) we started tracking coverage of the tests themselves, which is great, but stopped tracking coverage of *landlab* itself, which is not great. This pull request adds both to our coverage tracking.
> Add landlab and tests folder to coverage

- .github/workflows/test.yml
- docs/source/tutorials/flow_direction_and_accumulation/PriorityFlood_LandscapeEvolutionModel.ipynb
- docs/source/tutorials/flow_direction_and_accumulation/PriorityFlood_realDEMs.ipynb
- docs/source/tutorials/flow_direction_and_accumulation/the_Flow_Director_Accumulator_PriorityFlood.ipynb
- docs/source/tutorials/landscape_evolution/hylands/HyLandsTutorial.ipynb
- docs/source/tutorials/landscape_evolution/space/SPACE_large_scale_eroder_user_guide_and_examples.ipynb
- docs/source/tutorials/landscape_evolution/threshold_eroder/threshold_eroder.ipynb
- news/2129.misc
- noxfile.py
- pyproject.toml
- requirements/required.txt
- requirements/testing.txt
- tests/components/space/test_space_large_scale_eroder.py
- tests/components/threshold_eroder/test_threshold_eroder.py
The *richdem* tests require *richdem* to be installed via *conda*. I would, however, like to switch our CI from using *setup-miniconda* to use the *setup-python* action because it's faster, and mirrors the recommended way to install landlab (if not using *richdem*, anyway). To that end, I've broken out the *richdem* tests as a separate job that uses *setup-miniconda* to allow for the rest of the jobs to be able to use *setup-python*.
* Tests and notebooks that use *richdem* are now marked with the *pytest* tag, `richdem` (they can be run with `pytest -m richdem` or not run with `pytest -m 'not richdem'`).
* The *test-landlab* and *test-notebooks* are now run with *setup-python* and I've removed the *conda* backend from their corresponding sessions in the *noxfile*.
> Run the Landlab richdem tests as a separate job

- .github/workflows/test.yml
- news/2132.misc
- noxfile.py
GitHub Actions now provides *arm64* runners, so I've added them to our CI. We had been building *arm64* wheels using *QEMU* but that was sooooo slow (it took nearly an hour to build a wheel). It was so slow, if fact, that I had disabled those builds except when publishing to PyPI.
> Use arm64 runners to the CI

- .github/workflows/test.yml
- .pre-commit-config.yaml
- docs/source/development/index.md
- news/2017.misc
- pyproject.toml
- requirements/notebooks.txt
- src/landlab/components/flow_accum/lossy_flow_accumulator.py
This pull request adds support of Python 3.13 and drops support for Python 3.10.
It looks like the only issue is with the *netcdf4* package which doesn't yet support Python 3.13.
> Upgrade to Python 3.13

- .github/actions/build-bdist/action.yml
- .github/workflows/test.yml
I've added a new composite action, *build-bdst*, that builds wheels using *cibuildwheel*.
Duplicate of #2136.
> Add a new composite action that builds wheels

- .github/actions/run-tests/action.yml
- .github/workflows/test.yml
I've added a new composite action that runs the tests using *nox*.
> Add a new composite action that runs the tests

- docs/source/install/developer_install.md
- news/2155.docs
As pointed out by @pfeiffea in #1954, there is some formatting errors on our developer install page. We were missing some triple backticks (```` ``` ````) around the *bash* commands for running *conda* to install *Landlab*'s dependencies.
> Fix formatting error in developer install instructions

- news/2163.bugfix
- src/landlab/components/depth_dependent_taylor_soil_creep/hillslope_depth_dependent_taylor_flux.py
> Fix dimensional error in Courant number calculation in DepthDependentTaylorDiffuser

- AUTHORS.md
The user previously known as *amanaster2* is now *adalvis*, so I've updated this, along with her new last name, in our list of contributors.
Congratulations, @adalvis! 🎉
> Update amanaster2 in author list

- USEDBY.md
- news/2170.docs
describing the change has been added
---
Updates `USEDBY.rst` with references to papers using Landlab found through May 2025. Addresses issue #2170.
> Update reference list for spring 2025

- .github/actions/run-notebooks/action.yml
- .github/actions/run-tests/action.yml
- .github/workflows/quick.yml
- .github/workflows/test.yml
- news/2140.misc
I've added a new workflow, *quick.yml*, that is triggered by a push or pull request. This workflow only runs the tests for a single operating system (*macos-14*) and python version (3.13). The complete test suite is triggered only on a pull request and then run if it is "ready for review" (i.e. not a draft pr).
The idea here is that we don't need to run our entire battery of tests while the pr is in development because most issues can be found through the quicker tests. The full set of tests can take 45 minutes to run—that's 45 minutes of wall time. Because many of the tests are run in parallel, the actual cpu time is many hours.
I chose to run the quick tests using *macos-14* (arm) because it seemed to be the fastest.
> Add a quick test workflow
